<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\AdditionalTrack1;

/**
 * Builder for model AdditionalTrack1
 *
 * @see AdditionalTrack1
 */
class AdditionalTrack1Builder
{
    /**
     * @var AdditionalTrack1
     */
    private $instance;

    private function __construct(AdditionalTrack1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Additional Track 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new AdditionalTrack1());
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets language code field.
     *
     * @param string|null $value
     */
    public function languageCode(?string $value): self
    {
        $this->instance->setLanguageCode($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new Additional Track 1 object.
     */
    public function build(): AdditionalTrack1
    {
        return CoreHelper::clone($this->instance);
    }
}
