<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\AssetList1;

/**
 * Builder for model AssetList1
 *
 * @see AssetList1
 */
class AssetList1Builder
{
    /**
     * @var AssetList1
     */
    private $instance;

    private function __construct(AssetList1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Asset List 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new AssetList1());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param string|null $value
     */
    public function createdAt(?string $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets duration field.
     *
     * @param int|null $value
     */
    public function duration(?int $value): self
    {
        $this->instance->setDuration($value);
        return $this;
    }

    /**
     * Initializes a new Asset List 1 object.
     */
    public function build(): AssetList1
    {
        return CoreHelper::clone($this->instance);
    }
}
