<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Aws4;

/**
 * Builder for model Aws4
 *
 * @see Aws4
 */
class Aws4Builder
{
    /**
     * @var Aws4
     */
    private $instance;

    private function __construct(Aws4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Aws 4 Builder object.
     *
     * @param string $bucketName
     * @param string $bucketRegion
     * @param string $accessKey
     * @param string $secret
     */
    public static function init(string $bucketName, string $bucketRegion, string $accessKey, string $secret): self
    {
        return new self(new Aws4($bucketName, $bucketRegion, $accessKey, $secret));
    }

    /**
     * Sets base path field.
     *
     * @param string|null $value
     */
    public function basePath(?string $value): self
    {
        $this->instance->setBasePath($value);
        return $this;
    }

    /**
     * Sets endpoint field.
     *
     * @param string|null $value
     */
    public function endpoint(?string $value): self
    {
        $this->instance->setEndpoint($value);
        return $this;
    }

    /**
     * Initializes a new Aws 4 object.
     */
    public function build(): Aws4
    {
        return CoreHelper::clone($this->instance);
    }
}
