<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Azure;

/**
 * Builder for model Azure
 *
 * @see Azure
 */
class AzureBuilder
{
    /**
     * @var Azure
     */
    private $instance;

    private function __construct(Azure $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Azure Builder object.
     *
     * @param string $azureAccountName
     * @param string $azureContainerName
     * @param string $azureSharedToken
     * @param string $azurePath
     */
    public static function init(
        string $azureAccountName,
        string $azureContainerName,
        string $azureSharedToken,
        string $azurePath
    ): self {
        return new self(new Azure($azureAccountName, $azureContainerName, $azureSharedToken, $azurePath));
    }

    /**
     * Initializes a new Azure object.
     */
    public function build(): Azure
    {
        return CoreHelper::clone($this->instance);
    }
}
