<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\CallToAction;

/**
 * Builder for model CallToAction
 *
 * @see CallToAction
 */
class CallToActionBuilder
{
    /**
     * @var CallToAction
     */
    private $instance;

    private function __construct(CallToAction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Call To Action Builder object.
     */
    public static function init(): self
    {
        return new self(new CallToAction());
    }

    /**
     * Sets text field.
     *
     * @param string|null $value
     */
    public function text(?string $value): self
    {
        $this->instance->setText($value);
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets start time field.
     *
     * @param int|null $value
     */
    public function startTime(?int $value): self
    {
        $this->instance->setStartTime($value);
        return $this;
    }

    /**
     * Sets end time field.
     *
     * @param int|null $value
     */
    public function endTime(?int $value): self
    {
        $this->instance->setEndTime($value);
        return $this;
    }

    /**
     * Sets font color field.
     *
     * @param string|null $value
     */
    public function fontColor(?string $value): self
    {
        $this->instance->setFontColor($value);
        return $this;
    }

    /**
     * Sets background color field.
     *
     * @param string|null $value
     */
    public function backgroundColor(?string $value): self
    {
        $this->instance->setBackgroundColor($value);
        return $this;
    }

    /**
     * Sets position from top field.
     *
     * @param int|null $value
     */
    public function positionFromTop(?int $value): self
    {
        $this->instance->setPositionFromTop($value);
        return $this;
    }

    /**
     * Sets position from right field.
     *
     * @param string|null $value
     */
    public function positionFromRight(?string $value): self
    {
        $this->instance->setPositionFromRight($value);
        return $this;
    }

    /**
     * Initializes a new Call To Action object.
     */
    public function build(): CallToAction
    {
        return CoreHelper::clone($this->instance);
    }
}
