<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\ChannelSettings1;

/**
 * Builder for model ChannelSettings1
 *
 * @see ChannelSettings1
 */
class ChannelSettings1Builder
{
    /**
     * @var ChannelSettings1
     */
    private $instance;

    private function __construct(ChannelSettings1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Channel Settings 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new ChannelSettings1());
    }

    /**
     * Sets active field.
     *
     * @param bool|null $value
     */
    public function active(?bool $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Sets privacy type field.
     *
     * @param string|null $value
     */
    public function privacyType(?string $value): self
    {
        $this->instance->setPrivacyType($value);
        return $this;
    }

    /**
     * Initializes a new Channel Settings 1 object.
     */
    public function build(): ChannelSettings1
    {
        return CoreHelper::clone($this->instance);
    }
}
