<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Cloudflare;

/**
 * Builder for model Cloudflare
 *
 * @see Cloudflare
 */
class CloudflareBuilder
{
    /**
     * @var Cloudflare
     */
    private $instance;

    private function __construct(Cloudflare $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cloudflare Builder object.
     *
     * @param string $bucketName
     * @param string $accessKey
     * @param string $accountId
     * @param string $secret
     */
    public static function init(string $bucketName, string $accessKey, string $accountId, string $secret): self
    {
        return new self(new Cloudflare($bucketName, $accessKey, $accountId, $secret));
    }

    /**
     * Sets base path field.
     *
     * @param string|null $value
     */
    public function basePath(?string $value): self
    {
        $this->instance->setBasePath($value);
        return $this;
    }

    /**
     * Initializes a new Cloudflare object.
     */
    public function build(): Cloudflare
    {
        return CoreHelper::clone($this->instance);
    }
}
