<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Cloudflare2;

/**
 * Builder for model Cloudflare2
 *
 * @see Cloudflare2
 */
class Cloudflare2Builder
{
    /**
     * @var Cloudflare2
     */
    private $instance;

    private function __construct(Cloudflare2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cloudflare 2 Builder object.
     *
     * @param string $bucketName
     * @param string $accessKey
     * @param string $accountId
     * @param string $secret
     */
    public static function init(string $bucketName, string $accessKey, string $accountId, string $secret): self
    {
        return new self(new Cloudflare2($bucketName, $accessKey, $accountId, $secret));
    }

    /**
     * Sets base path field.
     *
     * @param string|null $value
     */
    public function basePath(?string $value): self
    {
        $this->instance->setBasePath($value);
        return $this;
    }

    /**
     * Initializes a new Cloudflare 2 object.
     */
    public function build(): Cloudflare2
    {
        return CoreHelper::clone($this->instance);
    }
}
