<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Cloudinary;

/**
 * Builder for model Cloudinary
 *
 * @see Cloudinary
 */
class CloudinaryBuilder
{
    /**
     * @var Cloudinary
     */
    private $instance;

    private function __construct(Cloudinary $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cloudinary Builder object.
     *
     * @param string $hostName
     * @param string $cloudName
     */
    public static function init(string $hostName, string $cloudName): self
    {
        return new self(new Cloudinary($hostName, $cloudName));
    }

    /**
     * Initializes a new Cloudinary object.
     */
    public function build(): Cloudinary
    {
        return CoreHelper::clone($this->instance);
    }
}
