<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Crop;

/**
 * Builder for model Crop
 *
 * @see Crop
 */
class CropBuilder
{
    /**
     * @var Crop
     */
    private $instance;

    private function __construct(Crop $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Crop Builder object.
     *
     * @param string $width
     * @param string $height
     */
    public static function init(string $width, string $height): self
    {
        return new self(new Crop($width, $height));
    }

    /**
     * Sets horizontal margin field.
     *
     * @param string|null $value
     */
    public function horizontalMargin(?string $value): self
    {
        $this->instance->setHorizontalMargin($value);
        return $this;
    }

    /**
     * Sets vertical margin field.
     *
     * @param string|null $value
     */
    public function verticalMargin(?string $value): self
    {
        $this->instance->setVerticalMargin($value);
        return $this;
    }

    /**
     * Initializes a new Crop object.
     */
    public function build(): Crop
    {
        return CoreHelper::clone($this->instance);
    }
}
