<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\DateRange;

/**
 * Builder for model DateRange
 *
 * @see DateRange
 */
class DateRangeBuilder
{
    /**
     * @var DateRange
     */
    private $instance;

    private function __construct(DateRange $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Date Range Builder object.
     */
    public static function init(): self
    {
        return new self(new DateRange());
    }

    /**
     * Sets start at field.
     *
     * @param \DateTime|null $value
     */
    public function startAt(?\DateTime $value): self
    {
        $this->instance->setStartAt($value);
        return $this;
    }

    /**
     * Sets end at field.
     *
     * @param \DateTime|null $value
     */
    public function endAt(?\DateTime $value): self
    {
        $this->instance->setEndAt($value);
        return $this;
    }

    /**
     * Initializes a new Date Range object.
     */
    public function build(): DateRange
    {
        return CoreHelper::clone($this->instance);
    }
}
