<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Error28;

/**
 * Builder for model Error28
 *
 * @see Error28
 */
class Error28Builder
{
    /**
     * @var Error28
     */
    private $instance;

    private function __construct(Error28 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error 28 Builder object.
     */
    public static function init(): self
    {
        return new self(new Error28());
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets extra field.
     *
     * @param array|null $value
     */
    public function extra(?array $value): self
    {
        $this->instance->setExtra($value);
        return $this;
    }

    /**
     * Sets param field.
     *
     * @param string|null $value
     */
    public function param(?string $value): self
    {
        $this->instance->setParam($value);
        return $this;
    }

    /**
     * Initializes a new Error 28 object.
     */
    public function build(): Error28
    {
        return CoreHelper::clone($this->instance);
    }
}
