<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Filters1;

/**
 * Builder for model Filters1
 *
 * @see Filters1
 */
class Filters1Builder
{
    /**
     * @var Filters1
     */
    private $instance;

    private function __construct(Filters1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Filters 1 Builder object.
     *
     * @param string $name
     * @param string $value
     */
    public static function init(string $name, string $value): self
    {
        return new self(new Filters1($name, $value));
    }

    /**
     * Sets operator field.
     *
     * @param string|null $value
     */
    public function operator(?string $value): self
    {
        $this->instance->setOperator($value);
        return $this;
    }

    /**
     * Initializes a new Filters 1 object.
     */
    public function build(): Filters1
    {
        return CoreHelper::clone($this->instance);
    }
}
