<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Gcs2;

/**
 * Builder for model Gcs2
 *
 * @see Gcs2
 */
class Gcs2Builder
{
    /**
     * @var Gcs2
     */
    private $instance;

    private function __construct(Gcs2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Gcs 2 Builder object.
     *
     * @param string $bucketName
     * @param string $serviceAccountKey
     */
    public static function init(string $bucketName, string $serviceAccountKey): self
    {
        return new self(new Gcs2($bucketName, $serviceAccountKey));
    }

    /**
     * Initializes a new Gcs 2 object.
     */
    public function build(): Gcs2
    {
        return CoreHelper::clone($this->instance);
    }
}
