<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\GenerateSubtitles;

/**
 * Builder for model GenerateSubtitles
 *
 * @see GenerateSubtitles
 */
class GenerateSubtitlesBuilder
{
    /**
     * @var GenerateSubtitles
     */
    private $instance;

    private function __construct(GenerateSubtitles $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Generate Subtitles Builder object.
     */
    public static function init(): self
    {
        return new self(new GenerateSubtitles());
    }

    /**
     * Sets audio language field.
     *
     * @param string|null $value
     */
    public function audioLanguage(?string $value): self
    {
        $this->instance->setAudioLanguage($value);
        return $this;
    }

    /**
     * Sets subtitle languages field.
     *
     * @param string|null $value
     */
    public function subtitleLanguages(?string $value): self
    {
        $this->instance->setSubtitleLanguages($value);
        return $this;
    }

    /**
     * Initializes a new Generate Subtitles object.
     */
    public function build(): GenerateSubtitles
    {
        return CoreHelper::clone($this->instance);
    }
}
