<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Aws4;
use GumletRestApisLib\Models\Azure2;
use GumletRestApisLib\Models\Backblaze2;
use GumletRestApisLib\Models\Cloudflare2;
use GumletRestApisLib\Models\Cloudinary2;
use GumletRestApisLib\Models\Dostorage2;
use GumletRestApisLib\Models\Gcs2;
use GumletRestApisLib\Models\ImageSourcesRequest;
use GumletRestApisLib\Models\Linode2;
use GumletRestApisLib\Models\Proxy2;
use GumletRestApisLib\Models\Wasabi2;

/**
 * Builder for model ImageSourcesRequest
 *
 * @see ImageSourcesRequest
 */
class ImageSourcesRequestBuilder
{
    /**
     * @var ImageSourcesRequest
     */
    private $instance;

    private function __construct(ImageSourcesRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Image Sources Request Builder object.
     *
     * @param string $namespace
     * @param string $type
     */
    public static function init(string $namespace, string $type): self
    {
        return new self(new ImageSourcesRequest($namespace, $type));
    }

    /**
     * Sets aws field.
     *
     * @param Aws4|null $value
     */
    public function aws(?Aws4 $value): self
    {
        $this->instance->setAws($value);
        return $this;
    }

    /**
     * Sets proxy field.
     *
     * @param Proxy2|null $value
     */
    public function proxy(?Proxy2 $value): self
    {
        $this->instance->setProxy($value);
        return $this;
    }

    /**
     * Sets gcs field.
     *
     * @param Gcs2|null $value
     */
    public function gcs(?Gcs2 $value): self
    {
        $this->instance->setGcs($value);
        return $this;
    }

    /**
     * Sets dostorage field.
     *
     * @param Dostorage2|null $value
     */
    public function dostorage(?Dostorage2 $value): self
    {
        $this->instance->setDostorage($value);
        return $this;
    }

    /**
     * Sets wasabi field.
     *
     * @param Wasabi2|null $value
     */
    public function wasabi(?Wasabi2 $value): self
    {
        $this->instance->setWasabi($value);
        return $this;
    }

    /**
     * Sets cloudinary field.
     *
     * @param Cloudinary2|null $value
     */
    public function cloudinary(?Cloudinary2 $value): self
    {
        $this->instance->setCloudinary($value);
        return $this;
    }

    /**
     * Sets azure field.
     *
     * @param Azure2|null $value
     */
    public function azure(?Azure2 $value): self
    {
        $this->instance->setAzure($value);
        return $this;
    }

    /**
     * Sets linode field.
     *
     * @param Linode2|null $value
     */
    public function linode(?Linode2 $value): self
    {
        $this->instance->setLinode($value);
        return $this;
    }

    /**
     * Sets backblaze field.
     *
     * @param Backblaze2|null $value
     */
    public function backblaze(?Backblaze2 $value): self
    {
        $this->instance->setBackblaze($value);
        return $this;
    }

    /**
     * Sets cloudflare field.
     *
     * @param Cloudflare2|null $value
     */
    public function cloudflare(?Cloudflare2 $value): self
    {
        $this->instance->setCloudflare($value);
        return $this;
    }

    /**
     * Initializes a new Image Sources Request object.
     */
    public function build(): ImageSourcesRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
