<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\ImageOverlay;

/**
 * Builder for model ImageOverlay
 *
 * @see ImageOverlay
 */
class ImageOverlayBuilder
{
    /**
     * @var ImageOverlay
     */
    private $instance;

    private function __construct(ImageOverlay $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Image Overlay Builder object.
     *
     * @param string $url
     */
    public static function init(string $url): self
    {
        return new self(new ImageOverlay($url));
    }

    /**
     * Sets horizontal margin field.
     *
     * @param string|null $value
     */
    public function horizontalMargin(?string $value): self
    {
        $this->instance->setHorizontalMargin($value);
        return $this;
    }

    /**
     * Sets vertical margin field.
     *
     * @param string|null $value
     */
    public function verticalMargin(?string $value): self
    {
        $this->instance->setVerticalMargin($value);
        return $this;
    }

    /**
     * Sets horizontal align field.
     *
     * @param string|null $value
     */
    public function horizontalAlign(?string $value): self
    {
        $this->instance->setHorizontalAlign($value);
        return $this;
    }

    /**
     * Sets vertical align field.
     *
     * @param string|null $value
     */
    public function verticalAlign(?string $value): self
    {
        $this->instance->setVerticalAlign($value);
        return $this;
    }

    /**
     * Sets width field.
     *
     * @param string|null $value
     */
    public function width(?string $value): self
    {
        $this->instance->setWidth($value);
        return $this;
    }

    /**
     * Sets height field.
     *
     * @param string|null $value
     */
    public function height(?string $value): self
    {
        $this->instance->setHeight($value);
        return $this;
    }

    /**
     * Initializes a new Image Overlay object.
     */
    public function build(): ImageOverlay
    {
        return CoreHelper::clone($this->instance);
    }
}
