<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\ImageAnalyticsResponse;
use GumletRestApisLib\Models\TopAsset;

/**
 * Builder for model ImageAnalyticsResponse
 *
 * @see ImageAnalyticsResponse
 */
class ImageAnalyticsResponseBuilder
{
    /**
     * @var ImageAnalyticsResponse
     */
    private $instance;

    private function __construct(ImageAnalyticsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Image Analytics Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ImageAnalyticsResponse());
    }

    /**
     * Sets top assets field.
     *
     * @param TopAsset[]|null $value
     */
    public function topAssets(?array $value): self
    {
        $this->instance->setTopAssets($value);
        return $this;
    }

    /**
     * Initializes a new Image Analytics Response object.
     */
    public function build(): ImageAnalyticsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
