<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\CallToAction3;
use GumletRestApisLib\Models\Input1;
use GumletRestApisLib\Models\Metadata;
use GumletRestApisLib\Models\Transformations1;

/**
 * Builder for model Input1
 *
 * @see Input1
 */
class Input1Builder
{
    /**
     * @var Input1
     */
    private $instance;

    private function __construct(Input1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Input 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Input1());
    }

    /**
     * Sets transformations field.
     *
     * @param Transformations1|null $value
     */
    public function transformations(?Transformations1 $value): self
    {
        $this->instance->setTransformations($value);
        return $this;
    }

    /**
     * Sets profile id field.
     *
     * @param string|null $value
     */
    public function profileId(?string $value): self
    {
        $this->instance->setProfileId($value);
        return $this;
    }

    /**
     * Sets title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets metadata field.
     *
     * @param Metadata|null $value
     */
    public function metadata(?Metadata $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets source url field.
     *
     * @param string|null $value
     */
    public function sourceUrl(?string $value): self
    {
        $this->instance->setSourceUrl($value);
        return $this;
    }

    /**
     * Sets call to actions field.
     *
     * @param CallToAction3[]|null $value
     */
    public function callToActions(?array $value): self
    {
        $this->instance->setCallToActions($value);
        return $this;
    }

    /**
     * Initializes a new Input 1 object.
     */
    public function build(): Input1
    {
        return CoreHelper::clone($this->instance);
    }
}
