<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Input4;

/**
 * Builder for model Input4
 *
 * @see Input4
 */
class Input4Builder
{
    /**
     * @var Input4
     */
    private $instance;

    private function __construct(Input4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Input 4 Builder object.
     */
    public static function init(): self
    {
        return new self(new Input4());
    }

    /**
     * Sets resolution field.
     *
     * @param string[]|null $value
     */
    public function resolution(?array $value): self
    {
        $this->instance->setResolution($value);
        return $this;
    }

    /**
     * Initializes a new Input 4 object.
     */
    public function build(): Input4
    {
        return CoreHelper::clone($this->instance);
    }
}
