<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Chapter;
use GumletRestApisLib\Models\Input2;
use GumletRestApisLib\Models\Transformations2;

/**
 * Builder for model Input2
 *
 * @see Input2
 */
class Input2Builder
{
    /**
     * @var Input2
     */
    private $instance;

    private function __construct(Input2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Input 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new Input2());
    }

    /**
     * Sets transformations field.
     *
     * @param Transformations2|null $value
     */
    public function transformations(?Transformations2 $value): self
    {
        $this->instance->setTransformations($value);
        return $this;
    }

    /**
     * Sets profile id field.
     *
     * @param string|null $value
     */
    public function profileId(?string $value): self
    {
        $this->instance->setProfileId($value);
        return $this;
    }

    /**
     * Sets title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets chapters field.
     *
     * @param Chapter[]|null $value
     */
    public function chapters(?array $value): self
    {
        $this->instance->setChapters($value);
        return $this;
    }

    /**
     * Sets source url field.
     *
     * @param string|null $value
     */
    public function sourceUrl(?string $value): self
    {
        $this->instance->setSourceUrl($value);
        return $this;
    }

    /**
     * Sets size field.
     *
     * @param int|null $value
     */
    public function size(?int $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Sets duration field.
     *
     * @param float|null $value
     */
    public function duration(?float $value): self
    {
        $this->instance->setDuration($value);
        return $this;
    }

    /**
     * Sets aspect ratio field.
     *
     * @param string|null $value
     */
    public function aspectRatio(?string $value): self
    {
        $this->instance->setAspectRatio($value);
        return $this;
    }

    /**
     * Sets fps field.
     *
     * @param float|null $value
     */
    public function fps(?float $value): self
    {
        $this->instance->setFps($value);
        return $this;
    }

    /**
     * Sets width field.
     *
     * @param int|null $value
     */
    public function width(?int $value): self
    {
        $this->instance->setWidth($value);
        return $this;
    }

    /**
     * Sets height field.
     *
     * @param int|null $value
     */
    public function height(?int $value): self
    {
        $this->instance->setHeight($value);
        return $this;
    }

    /**
     * Initializes a new Input 2 object.
     */
    public function build(): Input2
    {
        return CoreHelper::clone($this->instance);
    }
}
