<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\InsightsAggregatedDataResponse;
use GumletRestApisLib\Models\Views1;

/**
 * Builder for model InsightsAggregatedDataResponse
 *
 * @see InsightsAggregatedDataResponse
 */
class InsightsAggregatedDataResponseBuilder
{
    /**
     * @var InsightsAggregatedDataResponse
     */
    private $instance;

    private function __construct(InsightsAggregatedDataResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Insights Aggregated Data Response Builder object.
     */
    public static function init(): self
    {
        return new self(new InsightsAggregatedDataResponse());
    }

    /**
     * Sets views field.
     *
     * @param Views1|null $value
     */
    public function views(?Views1 $value): self
    {
        $this->instance->setViews($value);
        return $this;
    }

    /**
     * Initializes a new Insights Aggregated Data Response object.
     */
    public function build(): InsightsAggregatedDataResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
