<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\InsightsBreakdownDataResponse;
use GumletRestApisLib\Models\Views;

/**
 * Builder for model InsightsBreakdownDataResponse
 *
 * @see InsightsBreakdownDataResponse
 */
class InsightsBreakdownDataResponseBuilder
{
    /**
     * @var InsightsBreakdownDataResponse
     */
    private $instance;

    private function __construct(InsightsBreakdownDataResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Insights Breakdown Data Response Builder object.
     */
    public static function init(): self
    {
        return new self(new InsightsBreakdownDataResponse());
    }

    /**
     * Sets views field.
     *
     * @param Views|null $value
     */
    public function views(?Views $value): self
    {
        $this->instance->setViews($value);
        return $this;
    }

    /**
     * Initializes a new Insights Breakdown Data Response object.
     */
    public function build(): InsightsBreakdownDataResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
