<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Breakdown;
use GumletRestApisLib\Models\Filters1;
use GumletRestApisLib\Models\InsightsBreakdownDataRequest;
use GumletRestApisLib\Models\Timeframe1;

/**
 * Builder for model InsightsBreakdownDataRequest
 *
 * @see InsightsBreakdownDataRequest
 */
class InsightsBreakdownDataRequestBuilder
{
    /**
     * @var InsightsBreakdownDataRequest
     */
    private $instance;

    private function __construct(InsightsBreakdownDataRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Insights Breakdown Data Request Builder object.
     *
     * @param Breakdown[] $breakdowns
     * @param string $propertyId
     * @param Timeframe1 $timeframe
     */
    public static function init(array $breakdowns, string $propertyId, Timeframe1 $timeframe): self
    {
        return new self(new InsightsBreakdownDataRequest($breakdowns, $propertyId, $timeframe));
    }

    /**
     * Sets filters field.
     *
     * @param Filters1[]|null $value
     */
    public function filters(?array $value): self
    {
        $this->instance->setFilters($value);
        return $this;
    }

    /**
     * Initializes a new Insights Breakdown Data Request object.
     */
    public function build(): InsightsBreakdownDataRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
