<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Linode;

/**
 * Builder for model Linode
 *
 * @see Linode
 */
class LinodeBuilder
{
    /**
     * @var Linode
     */
    private $instance;

    private function __construct(Linode $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Linode Builder object.
     *
     * @param string $bucketName
     * @param string $bucketRegion
     * @param string $accessKey
     * @param string $secret
     */
    public static function init(string $bucketName, string $bucketRegion, string $accessKey, string $secret): self
    {
        return new self(new Linode($bucketName, $bucketRegion, $accessKey, $secret));
    }

    /**
     * Initializes a new Linode object.
     */
    public function build(): Linode
    {
        return CoreHelper::clone($this->instance);
    }
}
