<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Metadata;

/**
 * Builder for model Metadata
 *
 * @see Metadata
 */
class MetadataBuilder
{
    /**
     * @var Metadata
     */
    private $instance;

    private function __construct(Metadata $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Metadata Builder object.
     */
    public static function init(): self
    {
        return new self(new Metadata());
    }

    /**
     * Sets headermeta field.
     *
     * @param string|null $value
     */
    public function headermeta(?string $value): self
    {
        $this->instance->setHeadermeta($value);
        return $this;
    }

    /**
     * Initializes a new Metadata object.
     */
    public function build(): Metadata
    {
        return CoreHelper::clone($this->instance);
    }
}
