<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\OrgWebhooksResponse;

/**
 * Builder for model OrgWebhooksResponse
 *
 * @see OrgWebhooksResponse
 */
class OrgWebhooksResponseBuilder
{
    /**
     * @var OrgWebhooksResponse
     */
    private $instance;

    private function __construct(OrgWebhooksResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Org Webhooks Response Builder object.
     */
    public static function init(): self
    {
        return new self(new OrgWebhooksResponse());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets triggers field.
     *
     * @param string[]|null $value
     */
    public function triggers(?array $value): self
    {
        $this->instance->setTriggers($value);
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param string|null $value
     */
    public function createdAt(?string $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets updated at field.
     *
     * @param string|null $value
     */
    public function updatedAt(?string $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Sets sources field.
     *
     * @param string[]|null $value
     */
    public function sources(?array $value): self
    {
        $this->instance->setSources($value);
        return $this;
    }

    /**
     * Sets secret token field.
     *
     * @param string|null $value
     */
    public function secretToken(?string $value): self
    {
        $this->instance->setSecretToken($value);
        return $this;
    }

    /**
     * Initializes a new Org Webhooks Response object.
     */
    public function build(): OrgWebhooksResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
