<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Pad;

/**
 * Builder for model Pad
 *
 * @see Pad
 */
class PadBuilder
{
    /**
     * @var Pad
     */
    private $instance;

    private function __construct(Pad $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pad Builder object.
     */
    public static function init(): self
    {
        return new self(new Pad());
    }

    /**
     * Sets top field.
     *
     * @param string|null $value
     */
    public function top(?string $value): self
    {
        $this->instance->setTop($value);
        return $this;
    }

    /**
     * Sets left field.
     *
     * @param string|null $value
     */
    public function left(?string $value): self
    {
        $this->instance->setLeft($value);
        return $this;
    }

    /**
     * Sets bottom field.
     *
     * @param string|null $value
     */
    public function bottom(?string $value): self
    {
        $this->instance->setBottom($value);
        return $this;
    }

    /**
     * Sets right field.
     *
     * @param string|null $value
     */
    public function right(?string $value): self
    {
        $this->instance->setRight($value);
        return $this;
    }

    /**
     * Sets color field.
     *
     * @param string|null $value
     */
    public function color(?string $value): self
    {
        $this->instance->setColor($value);
        return $this;
    }

    /**
     * Initializes a new Pad object.
     */
    public function build(): Pad
    {
        return CoreHelper::clone($this->instance);
    }
}
