<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Part;

/**
 * Builder for model Part
 *
 * @see Part
 */
class PartBuilder
{
    /**
     * @var Part
     */
    private $instance;

    private function __construct(Part $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Part Builder object.
     */
    public static function init(): self
    {
        return new self(new Part());
    }

    /**
     * Sets Part Number field.
     *
     * @param int|null $value
     */
    public function partNumber(?int $value): self
    {
        $this->instance->setPartNumber($value);
        return $this;
    }

    /**
     * Sets E Tag field.
     *
     * @param string|null $value
     */
    public function eTag(?string $value): self
    {
        $this->instance->setETag($value);
        return $this;
    }

    /**
     * Initializes a new Part object.
     */
    public function build(): Part
    {
        return CoreHelper::clone($this->instance);
    }
}
