<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\PreviewThumbnail;

/**
 * Builder for model PreviewThumbnail
 *
 * @see PreviewThumbnail
 */
class PreviewThumbnailBuilder
{
    /**
     * @var PreviewThumbnail
     */
    private $instance;

    private function __construct(PreviewThumbnail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Preview Thumbnail Builder object.
     */
    public static function init(): self
    {
        return new self(new PreviewThumbnail());
    }

    /**
     * Sets file Name field.
     *
     * @param string|null $value
     */
    public function fileName(?string $value): self
    {
        $this->instance->setFileName($value);
        return $this;
    }

    /**
     * Sets size field.
     *
     * @param int|null $value
     */
    public function size(?int $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Initializes a new Preview Thumbnail object.
     */
    public function build(): PreviewThumbnail
    {
        return CoreHelper::clone($this->instance);
    }
}
