<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\PreviewThumbnails;

/**
 * Builder for model PreviewThumbnails
 *
 * @see PreviewThumbnails
 */
class PreviewThumbnailsBuilder
{
    /**
     * @var PreviewThumbnails
     */
    private $instance;

    private function __construct(PreviewThumbnails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Preview Thumbnails Builder object.
     */
    public static function init(): self
    {
        return new self(new PreviewThumbnails());
    }

    /**
     * Sets max tiles field.
     *
     * @param int|null $value
     */
    public function maxTiles(?int $value): self
    {
        $this->instance->setMaxTiles($value);
        return $this;
    }

    /**
     * Initializes a new Preview Thumbnails object.
     */
    public function build(): PreviewThumbnails
    {
        return CoreHelper::clone($this->instance);
    }
}
