<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Proxy;

/**
 * Builder for model Proxy
 *
 * @see Proxy
 */
class ProxyBuilder
{
    /**
     * @var Proxy
     */
    private $instance;

    private function __construct(Proxy $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Proxy Builder object.
     *
     * @param string $whitelistedDomains
     */
    public static function init(string $whitelistedDomains): self
    {
        return new self(new Proxy($whitelistedDomains));
    }

    /**
     * Initializes a new Proxy object.
     */
    public function build(): Proxy
    {
        return CoreHelper::clone($this->instance);
    }
}
