<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Proxy2;

/**
 * Builder for model Proxy2
 *
 * @see Proxy2
 */
class Proxy2Builder
{
    /**
     * @var Proxy2
     */
    private $instance;

    private function __construct(Proxy2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Proxy 2 Builder object.
     *
     * @param string $whitelistedDomains
     */
    public static function init(string $whitelistedDomains): self
    {
        return new self(new Proxy2($whitelistedDomains));
    }

    /**
     * Initializes a new Proxy 2 object.
     */
    public function build(): Proxy2
    {
        return CoreHelper::clone($this->instance);
    }
}
