<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\PurgeRequest;

/**
 * Builder for model PurgeRequest
 *
 * @see PurgeRequest
 */
class PurgeRequestBuilder
{
    /**
     * @var PurgeRequest
     */
    private $instance;

    private function __construct(PurgeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Purge Request Builder object.
     */
    public static function init(): self
    {
        return new self(new PurgeRequest());
    }

    /**
     * Sets paths field.
     *
     * @param string[]|null $value
     */
    public function paths(?array $value): self
    {
        $this->instance->setPaths($value);
        return $this;
    }

    /**
     * Initializes a new Purge Request object.
     */
    public function build(): PurgeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
