<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Audio;
use GumletRestApisLib\Models\Playlist;
use GumletRestApisLib\Models\PreviewThumbnail;
use GumletRestApisLib\Models\StorageDetails;
use GumletRestApisLib\Models\Subtitle;
use GumletRestApisLib\Models\Thumbnail;
use GumletRestApisLib\Models\Video;

/**
 * Builder for model StorageDetails
 *
 * @see StorageDetails
 */
class StorageDetailsBuilder
{
    /**
     * @var StorageDetails
     */
    private $instance;

    private function __construct(StorageDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Storage Details Builder object.
     */
    public static function init(): self
    {
        return new self(new StorageDetails());
    }

    /**
     * Sets video field.
     *
     * @param Video[]|null $value
     */
    public function video(?array $value): self
    {
        $this->instance->setVideo($value);
        return $this;
    }

    /**
     * Sets audio field.
     *
     * @param Audio[]|null $value
     */
    public function audio(?array $value): self
    {
        $this->instance->setAudio($value);
        return $this;
    }

    /**
     * Sets playlist field.
     *
     * @param Playlist[]|null $value
     */
    public function playlist(?array $value): self
    {
        $this->instance->setPlaylist($value);
        return $this;
    }

    /**
     * Sets thumbnail field.
     *
     * @param Thumbnail[]|null $value
     */
    public function thumbnail(?array $value): self
    {
        $this->instance->setThumbnail($value);
        return $this;
    }

    /**
     * Sets subtitle field.
     *
     * @param Subtitle[]|null $value
     */
    public function subtitle(?array $value): self
    {
        $this->instance->setSubtitle($value);
        return $this;
    }

    /**
     * Sets preview Thumbnail field.
     *
     * @param PreviewThumbnail[]|null $value
     */
    public function previewThumbnail(?array $value): self
    {
        $this->instance->setPreviewThumbnail($value);
        return $this;
    }

    /**
     * Initializes a new Storage Details object.
     */
    public function build(): StorageDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
