<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Subtitle;

/**
 * Builder for model Subtitle
 *
 * @see Subtitle
 */
class SubtitleBuilder
{
    /**
     * @var Subtitle
     */
    private $instance;

    private function __construct(Subtitle $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Subtitle Builder object.
     */
    public static function init(): self
    {
        return new self(new Subtitle());
    }

    /**
     * Sets file Name field.
     *
     * @param string|null $value
     */
    public function fileName(?string $value): self
    {
        $this->instance->setFileName($value);
        return $this;
    }

    /**
     * Sets size field.
     *
     * @param int|null $value
     */
    public function size(?int $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Initializes a new Subtitle object.
     */
    public function build(): Subtitle
    {
        return CoreHelper::clone($this->instance);
    }
}
