<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Thumbnail;

/**
 * Builder for model Thumbnail
 *
 * @see Thumbnail
 */
class ThumbnailBuilder
{
    /**
     * @var Thumbnail
     */
    private $instance;

    private function __construct(Thumbnail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Thumbnail Builder object.
     */
    public static function init(): self
    {
        return new self(new Thumbnail());
    }

    /**
     * Sets file Name field.
     *
     * @param string|null $value
     */
    public function fileName(?string $value): self
    {
        $this->instance->setFileName($value);
        return $this;
    }

    /**
     * Sets size field.
     *
     * @param int|null $value
     */
    public function size(?int $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Sets resolution field.
     *
     * @param string|null $value
     */
    public function resolution(?string $value): self
    {
        $this->instance->setResolution($value);
        return $this;
    }

    /**
     * Initializes a new Thumbnail object.
     */
    public function build(): Thumbnail
    {
        return CoreHelper::clone($this->instance);
    }
}
