<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Timeframe1;

/**
 * Builder for model Timeframe1
 *
 * @see Timeframe1
 */
class Timeframe1Builder
{
    /**
     * @var Timeframe1
     */
    private $instance;

    private function __construct(Timeframe1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Timeframe 1 Builder object.
     *
     * @param \DateTime $startAt
     * @param \DateTime $endAt
     */
    public static function init(\DateTime $startAt, \DateTime $endAt): self
    {
        return new self(new Timeframe1($startAt, $endAt));
    }

    /**
     * Initializes a new Timeframe 1 object.
     */
    public function build(): Timeframe1
    {
        return CoreHelper::clone($this->instance);
    }
}
