<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Timeframe;

/**
 * Builder for model Timeframe
 *
 * @see Timeframe
 */
class TimeframeBuilder
{
    /**
     * @var Timeframe
     */
    private $instance;

    private function __construct(Timeframe $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Timeframe Builder object.
     *
     * @param \DateTime $startAt
     * @param \DateTime $endAt
     */
    public static function init(\DateTime $startAt, \DateTime $endAt): self
    {
        return new self(new Timeframe($startAt, $endAt));
    }

    /**
     * Initializes a new Timeframe object.
     */
    public function build(): Timeframe
    {
        return CoreHelper::clone($this->instance);
    }
}
