<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Transformations3;

/**
 * Builder for model Transformations3
 *
 * @see Transformations3
 */
class Transformations3Builder
{
    /**
     * @var Transformations3
     */
    private $instance;

    private function __construct(Transformations3 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transformations 3 Builder object.
     */
    public static function init(): self
    {
        return new self(new Transformations3());
    }

    /**
     * Sets resolution field.
     *
     * @param string|null $value
     */
    public function resolution(?string $value): self
    {
        $this->instance->setResolution($value);
        return $this;
    }

    /**
     * Sets format field.
     *
     * @param string|null $value
     */
    public function format(?string $value): self
    {
        $this->instance->setFormat($value);
        return $this;
    }

    /**
     * Sets audio codec field.
     *
     * @param string[]|null $value
     */
    public function audioCodec(?array $value): self
    {
        $this->instance->setAudioCodec($value);
        return $this;
    }

    /**
     * Sets video codec field.
     *
     * @param string[]|null $value
     */
    public function videoCodec(?array $value): self
    {
        $this->instance->setVideoCodec($value);
        return $this;
    }

    /**
     * Sets thumbnail field.
     *
     * @param string[]|null $value
     */
    public function thumbnail(?array $value): self
    {
        $this->instance->setThumbnail($value);
        return $this;
    }

    /**
     * Sets thumbnail format field.
     *
     * @param string|null $value
     */
    public function thumbnailFormat(?string $value): self
    {
        $this->instance->setThumbnailFormat($value);
        return $this;
    }

    /**
     * Sets mp 4 access field.
     *
     * @param bool|null $value
     */
    public function mp4Access(?bool $value): self
    {
        $this->instance->setMp4Access($value);
        return $this;
    }

    /**
     * Sets audio only field.
     *
     * @param bool|null $value
     */
    public function audioOnly(?bool $value): self
    {
        $this->instance->setAudioOnly($value);
        return $this;
    }

    /**
     * Sets keep original field.
     *
     * @param bool|null $value
     */
    public function keepOriginal(?bool $value): self
    {
        $this->instance->setKeepOriginal($value);
        return $this;
    }

    /**
     * Sets per title encoding field.
     *
     * @param bool|null $value
     */
    public function perTitleEncoding(?bool $value): self
    {
        $this->instance->setPerTitleEncoding($value);
        return $this;
    }

    /**
     * Sets process low resolution input field.
     *
     * @param bool|null $value
     */
    public function processLowResolutionInput(?bool $value): self
    {
        $this->instance->setProcessLowResolutionInput($value);
        return $this;
    }

    /**
     * Initializes a new Transformations 3 object.
     */
    public function build(): Transformations3
    {
        return CoreHelper::clone($this->instance);
    }
}
