<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Transformations6;

/**
 * Builder for model Transformations6
 *
 * @see Transformations6
 */
class Transformations6Builder
{
    /**
     * @var Transformations6
     */
    private $instance;

    private function __construct(Transformations6 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transformations 6 Builder object.
     */
    public static function init(): self
    {
        return new self(new Transformations6());
    }

    /**
     * Sets resolution field.
     *
     * @param string|null $value
     */
    public function resolution(?string $value): self
    {
        $this->instance->setResolution($value);
        return $this;
    }

    /**
     * Sets format field.
     *
     * @param string|null $value
     */
    public function format(?string $value): self
    {
        $this->instance->setFormat($value);
        return $this;
    }

    /**
     * Sets audio codec field.
     *
     * @param string[]|null $value
     */
    public function audioCodec(?array $value): self
    {
        $this->instance->setAudioCodec($value);
        return $this;
    }

    /**
     * Sets video codec field.
     *
     * @param string[]|null $value
     */
    public function videoCodec(?array $value): self
    {
        $this->instance->setVideoCodec($value);
        return $this;
    }

    /**
     * Sets thumbnail field.
     *
     * @param string[]|null $value
     */
    public function thumbnail(?array $value): self
    {
        $this->instance->setThumbnail($value);
        return $this;
    }

    /**
     * Sets thumbnail format field.
     *
     * @param string|null $value
     */
    public function thumbnailFormat(?string $value): self
    {
        $this->instance->setThumbnailFormat($value);
        return $this;
    }

    /**
     * Sets mp 4 access field.
     *
     * @param bool|null $value
     */
    public function mp4Access(?bool $value): self
    {
        $this->instance->setMp4Access($value);
        return $this;
    }

    /**
     * Sets per title encoding field.
     *
     * @param bool|null $value
     */
    public function perTitleEncoding(?bool $value): self
    {
        $this->instance->setPerTitleEncoding($value);
        return $this;
    }

    /**
     * Initializes a new Transformations 6 object.
     */
    public function build(): Transformations6
    {
        return CoreHelper::clone($this->instance);
    }
}
