<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\VideoAssetsSubtitleUploadRequest;

/**
 * Builder for model VideoAssetsSubtitleUploadRequest
 *
 * @see VideoAssetsSubtitleUploadRequest
 */
class VideoAssetsSubtitleUploadRequestBuilder
{
    /**
     * @var VideoAssetsSubtitleUploadRequest
     */
    private $instance;

    private function __construct(VideoAssetsSubtitleUploadRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Assets Subtitle Upload Request Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoAssetsSubtitleUploadRequest());
    }

    /**
     * Sets language codes field.
     *
     * @param string[]|null $value
     */
    public function languageCodes(?array $value): self
    {
        $this->instance->setLanguageCodes($value);
        return $this;
    }

    /**
     * Initializes a new Video Assets Subtitle Upload Request object.
     */
    public function build(): VideoAssetsSubtitleUploadRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
