<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Datum;
use GumletRestApisLib\Models\VideoStreamingDurationResponse;

/**
 * Builder for model VideoStreamingDurationResponse
 *
 * @see VideoStreamingDurationResponse
 */
class VideoStreamingDurationResponseBuilder
{
    /**
     * @var VideoStreamingDurationResponse
     */
    private $instance;

    private function __construct(VideoStreamingDurationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Streaming Duration Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoStreamingDurationResponse());
    }

    /**
     * Sets data field.
     *
     * @param Datum[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets has next page field.
     *
     * @param bool|null $value
     */
    public function hasNextPage(?bool $value): self
    {
        $this->instance->setHasNextPage($value);
        return $this;
    }

    /**
     * Initializes a new Video Streaming Duration Response object.
     */
    public function build(): VideoStreamingDurationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
