<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\VideoPlaylistRequest;

/**
 * Builder for model VideoPlaylistRequest
 *
 * @see VideoPlaylistRequest
 */
class VideoPlaylistRequestBuilder
{
    /**
     * @var VideoPlaylistRequest
     */
    private $instance;

    private function __construct(VideoPlaylistRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Playlist Request Builder object.
     *
     * @param string $collectionId
     * @param string $title
     */
    public static function init(string $collectionId, string $title): self
    {
        return new self(new VideoPlaylistRequest($collectionId, $title));
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new Video Playlist Request object.
     */
    public function build(): VideoPlaylistRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
