<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Chapter1;
use GumletRestApisLib\Models\VideoAssetsChaptersRequest;

/**
 * Builder for model VideoAssetsChaptersRequest
 *
 * @see VideoAssetsChaptersRequest
 */
class VideoAssetsChaptersRequestBuilder
{
    /**
     * @var VideoAssetsChaptersRequest
     */
    private $instance;

    private function __construct(VideoAssetsChaptersRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Assets Chapters Request Builder object.
     *
     * @param Chapter1[] $chapters
     */
    public static function init(array $chapters): self
    {
        return new self(new VideoAssetsChaptersRequest($chapters));
    }

    /**
     * Initializes a new Video Assets Chapters Request object.
     */
    public function build(): VideoAssetsChaptersRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
