<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\UploadResponse;
use GumletRestApisLib\Models\VideoAssetsSubtitleUploadEventRequest;

/**
 * Builder for model VideoAssetsSubtitleUploadEventRequest
 *
 * @see VideoAssetsSubtitleUploadEventRequest
 */
class VideoAssetsSubtitleUploadEventRequestBuilder
{
    /**
     * @var VideoAssetsSubtitleUploadEventRequest
     */
    private $instance;

    private function __construct(VideoAssetsSubtitleUploadEventRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Assets Subtitle Upload Event Request Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoAssetsSubtitleUploadEventRequest());
    }

    /**
     * Sets upload responses field.
     *
     * @param UploadResponse[]|null $value
     */
    public function uploadResponses(?array $value): self
    {
        $this->instance->setUploadResponses($value);
        return $this;
    }

    /**
     * Initializes a new Video Assets Subtitle Upload Event Request object.
     */
    public function build(): VideoAssetsSubtitleUploadEventRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
