<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\AssetList;
use GumletRestApisLib\Models\VideoPlaylistAssetRequest;

/**
 * Builder for model VideoPlaylistAssetRequest
 *
 * @see VideoPlaylistAssetRequest
 */
class VideoPlaylistAssetRequestBuilder
{
    /**
     * @var VideoPlaylistAssetRequest
     */
    private $instance;

    private function __construct(VideoPlaylistAssetRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Playlist Asset Request Builder object.
     *
     * @param AssetList[] $assetList
     */
    public static function init(array $assetList): self
    {
        return new self(new VideoPlaylistAssetRequest($assetList));
    }

    /**
     * Initializes a new Video Playlist Asset Request object.
     */
    public function build(): VideoPlaylistAssetRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
