<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\AllAsset;
use GumletRestApisLib\Models\VideoAssetsListResponse;

/**
 * Builder for model VideoAssetsListResponse
 *
 * @see VideoAssetsListResponse
 */
class VideoAssetsListResponseBuilder
{
    /**
     * @var VideoAssetsListResponse
     */
    private $instance;

    private function __construct(VideoAssetsListResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Assets List Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoAssetsListResponse());
    }

    /**
     * Sets all assets field.
     *
     * @param AllAsset[]|null $value
     */
    public function allAssets(?array $value): self
    {
        $this->instance->setAllAssets($value);
        return $this;
    }

    /**
     * Sets total asset count field.
     *
     * @param int|null $value
     */
    public function totalAssetCount(?int $value): self
    {
        $this->instance->setTotalAssetCount($value);
        return $this;
    }

    /**
     * Sets current offset field.
     *
     * @param int|null $value
     */
    public function currentOffset(?int $value): self
    {
        $this->instance->setCurrentOffset($value);
        return $this;
    }

    /**
     * Sets distinct tags field.
     *
     * @param string[]|null $value
     */
    public function distinctTags(?array $value): self
    {
        $this->instance->setDistinctTags($value);
        return $this;
    }

    /**
     * Initializes a new Video Assets List Response object.
     */
    public function build(): VideoAssetsListResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
