<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\AllSource;
use GumletRestApisLib\Models\VideoSourcesResponse;

/**
 * Builder for model VideoSourcesResponse
 *
 * @see VideoSourcesResponse
 */
class VideoSourcesResponseBuilder
{
    /**
     * @var VideoSourcesResponse
     */
    private $instance;

    private function __construct(VideoSourcesResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Sources Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoSourcesResponse());
    }

    /**
     * Sets all sources field.
     *
     * @param AllSource[]|null $value
     */
    public function allSources(?array $value): self
    {
        $this->instance->setAllSources($value);
        return $this;
    }

    /**
     * Initializes a new Video Sources Response object.
     */
    public function build(): VideoSourcesResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
