<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\VideoProtection1;

/**
 * Builder for model VideoProtection1
 *
 * @see VideoProtection1
 */
class VideoProtection1Builder
{
    /**
     * @var VideoProtection1
     */
    private $instance;

    private function __construct(VideoProtection1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Protection 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoProtection1());
    }

    /**
     * Sets signed url field.
     *
     * @param bool|null $value
     */
    public function signedUrl(?bool $value): self
    {
        $this->instance->setSignedUrl($value);
        return $this;
    }

    /**
     * Sets signed url secret field.
     *
     * @param string|null $value
     */
    public function signedUrlSecret(?string $value): self
    {
        $this->instance->setSignedUrlSecret($value);
        return $this;
    }

    /**
     * Sets blacklisted countries field.
     *
     * @param string[]|null $value
     */
    public function blacklistedCountries(?array $value): self
    {
        $this->instance->setBlacklistedCountries($value);
        return $this;
    }

    /**
     * Sets whitelisted referrers field.
     *
     * @param string|null $value
     */
    public function whitelistedReferrers(?string $value): self
    {
        $this->instance->setWhitelistedReferrers($value);
        return $this;
    }

    /**
     * Initializes a new Video Protection 1 object.
     */
    public function build(): VideoProtection1
    {
        return CoreHelper::clone($this->instance);
    }
}
