<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\VideoPlaylistAssetResponse;

/**
 * Builder for model VideoPlaylistAssetResponse
 *
 * @see VideoPlaylistAssetResponse
 */
class VideoPlaylistAssetResponseBuilder
{
    /**
     * @var VideoPlaylistAssetResponse
     */
    private $instance;

    private function __construct(VideoPlaylistAssetResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Playlist Asset Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoPlaylistAssetResponse());
    }

    /**
     * Sets success field.
     *
     * @param bool|null $value
     */
    public function success(?bool $value): self
    {
        $this->instance->setSuccess($value);
        return $this;
    }

    /**
     * Initializes a new Video Playlist Asset Response object.
     */
    public function build(): VideoPlaylistAssetResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
