<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\DateRange;
use GumletRestApisLib\Models\Filters;
use GumletRestApisLib\Models\VideoAnalyticsRequest;

/**
 * Builder for model VideoAnalyticsRequest
 *
 * @see VideoAnalyticsRequest
 */
class VideoAnalyticsRequestBuilder
{
    /**
     * @var VideoAnalyticsRequest
     */
    private $instance;

    private function __construct(VideoAnalyticsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Analytics Request Builder object.
     *
     * @param string[] $metrics
     * @param DateRange $dateRange
     */
    public static function init(array $metrics, DateRange $dateRange): self
    {
        return new self(new VideoAnalyticsRequest($metrics, $dateRange));
    }

    /**
     * Sets top assets count field.
     *
     * @param int|null $value
     */
    public function topAssetsCount(?int $value): self
    {
        $this->instance->setTopAssetsCount($value);
        return $this;
    }

    /**
     * Sets filters field.
     *
     * @param Filters|null $value
     */
    public function filters(?Filters $value): self
    {
        $this->instance->setFilters($value);
        return $this;
    }

    /**
     * Initializes a new Video Analytics Request object.
     */
    public function build(): VideoAnalyticsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
