<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\CallToAction;
use GumletRestApisLib\Models\GenerateSubtitles3;
use GumletRestApisLib\Models\VideoAssetsUpdateRequest;

/**
 * Builder for model VideoAssetsUpdateRequest
 *
 * @see VideoAssetsUpdateRequest
 */
class VideoAssetsUpdateRequestBuilder
{
    /**
     * @var VideoAssetsUpdateRequest
     */
    private $instance;

    private function __construct(VideoAssetsUpdateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Assets Update Request Builder object.
     *
     * @param string $assetId
     */
    public static function init(string $assetId): self
    {
        return new self(new VideoAssetsUpdateRequest($assetId));
    }

    /**
     * Sets title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets tag field.
     *
     * @param string|null $value
     */
    public function tag(?string $value): self
    {
        $this->instance->setTag($value);
        return $this;
    }

    /**
     * Sets call to actions field.
     *
     * @param CallToAction[]|null $value
     */
    public function callToActions(?array $value): self
    {
        $this->instance->setCallToActions($value);
        return $this;
    }

    /**
     * Sets metadata field.
     *
     * @param string|null $value
     */
    public function metadata(?string $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets remove subtitles field.
     *
     * @param string[]|null $value
     */
    public function removeSubtitles(?array $value): self
    {
        $this->instance->setRemoveSubtitles($value);
        return $this;
    }

    /**
     * Sets generate subtitles field.
     *
     * @param GenerateSubtitles3|null $value
     */
    public function generateSubtitles(?GenerateSubtitles3 $value): self
    {
        $this->instance->setGenerateSubtitles($value);
        return $this;
    }

    /**
     * Initializes a new Video Assets Update Request object.
     */
    public function build(): VideoAssetsUpdateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
