<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\VideoPlaylistAssetRequest1;

/**
 * Builder for model VideoPlaylistAssetRequest1
 *
 * @see VideoPlaylistAssetRequest1
 */
class VideoPlaylistAssetRequest1Builder
{
    /**
     * @var VideoPlaylistAssetRequest1
     */
    private $instance;

    private function __construct(VideoPlaylistAssetRequest1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Playlist Asset Request 1 Builder object.
     *
     * @param string[] $deleteList
     */
    public static function init(array $deleteList): self
    {
        return new self(new VideoPlaylistAssetRequest1($deleteList));
    }

    /**
     * Initializes a new Video Playlist Asset Request 1 object.
     */
    public function build(): VideoPlaylistAssetRequest1
    {
        return CoreHelper::clone($this->instance);
    }
}
