<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\VideoProtection;

/**
 * Builder for model VideoProtection
 *
 * @see VideoProtection
 */
class VideoProtectionBuilder
{
    /**
     * @var VideoProtection
     */
    private $instance;

    private function __construct(VideoProtection $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Protection Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoProtection());
    }

    /**
     * Sets signed url field.
     *
     * @param bool|null $value
     */
    public function signedUrl(?bool $value): self
    {
        $this->instance->setSignedUrl($value);
        return $this;
    }

    /**
     * Sets signed url secret field.
     *
     * @param string|null $value
     */
    public function signedUrlSecret(?string $value): self
    {
        $this->instance->setSignedUrlSecret($value);
        return $this;
    }

    /**
     * Initializes a new Video Protection object.
     */
    public function build(): VideoProtection
    {
        return CoreHelper::clone($this->instance);
    }
}
