<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Part;
use GumletRestApisLib\Models\VideoAssetsMultipartuploadCompleteRequest;

/**
 * Builder for model VideoAssetsMultipartuploadCompleteRequest
 *
 * @see VideoAssetsMultipartuploadCompleteRequest
 */
class VideoAssetsMultipartuploadCompleteRequestBuilder
{
    /**
     * @var VideoAssetsMultipartuploadCompleteRequest
     */
    private $instance;

    private function __construct(VideoAssetsMultipartuploadCompleteRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Assets Multipartupload Complete Request Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoAssetsMultipartuploadCompleteRequest());
    }

    /**
     * Sets parts field.
     *
     * @param Part[]|null $value
     */
    public function parts(?array $value): self
    {
        $this->instance->setParts($value);
        return $this;
    }

    /**
     * Initializes a new Video Assets Multipartupload Complete Request object.
     */
    public function build(): VideoAssetsMultipartuploadCompleteRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
