<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\VideoAssetsThumbnailRequest;

/**
 * Builder for model VideoAssetsThumbnailRequest
 *
 * @see VideoAssetsThumbnailRequest
 */
class VideoAssetsThumbnailRequestBuilder
{
    /**
     * @var VideoAssetsThumbnailRequest
     */
    private $instance;

    private function __construct(VideoAssetsThumbnailRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Assets Thumbnail Request Builder object.
     *
     * @param int $frameAtSecond
     */
    public static function init(int $frameAtSecond): self
    {
        return new self(new VideoAssetsThumbnailRequest($frameAtSecond));
    }

    /**
     * Initializes a new Video Assets Thumbnail Request object.
     */
    public function build(): VideoAssetsThumbnailRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
