<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Transformations6;
use GumletRestApisLib\Models\VideoProfilesResponse2;

/**
 * Builder for model VideoProfilesResponse2
 *
 * @see VideoProfilesResponse2
 */
class VideoProfilesResponse2Builder
{
    /**
     * @var VideoProfilesResponse2
     */
    private $instance;

    private function __construct(VideoProfilesResponse2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Profiles Response 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoProfilesResponse2());
    }

    /**
     * Sets profile id field.
     *
     * @param string|null $value
     */
    public function profileId(?string $value): self
    {
        $this->instance->setProfileId($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets transformations field.
     *
     * @param Transformations6|null $value
     */
    public function transformations(?Transformations6 $value): self
    {
        $this->instance->setTransformations($value);
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param int|null $value
     */
    public function createdAt(?int $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets updated at field.
     *
     * @param int|null $value
     */
    public function updatedAt(?int $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Initializes a new Video Profiles Response 2 object.
     */
    public function build(): VideoProfilesResponse2
    {
        return CoreHelper::clone($this->instance);
    }
}
