<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\AllLiveAsset;
use GumletRestApisLib\Models\VideoLiveAssetsListResponse;

/**
 * Builder for model VideoLiveAssetsListResponse
 *
 * @see VideoLiveAssetsListResponse
 */
class VideoLiveAssetsListResponseBuilder
{
    /**
     * @var VideoLiveAssetsListResponse
     */
    private $instance;

    private function __construct(VideoLiveAssetsListResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Live Assets List Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoLiveAssetsListResponse());
    }

    /**
     * Sets all live assets field.
     *
     * @param AllLiveAsset[]|null $value
     */
    public function allLiveAssets(?array $value): self
    {
        $this->instance->setAllLiveAssets($value);
        return $this;
    }

    /**
     * Sets total live asset count field.
     *
     * @param int|null $value
     */
    public function totalLiveAssetCount(?int $value): self
    {
        $this->instance->setTotalLiveAssetCount($value);
        return $this;
    }

    /**
     * Sets current offset field.
     *
     * @param int|null $value
     */
    public function currentOffset(?int $value): self
    {
        $this->instance->setCurrentOffset($value);
        return $this;
    }

    /**
     * Initializes a new Video Live Assets List Response object.
     */
    public function build(): VideoLiveAssetsListResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
