<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\AssetList1;
use GumletRestApisLib\Models\VideoPlaylistAssetsResponse;

/**
 * Builder for model VideoPlaylistAssetsResponse
 *
 * @see VideoPlaylistAssetsResponse
 */
class VideoPlaylistAssetsResponseBuilder
{
    /**
     * @var VideoPlaylistAssetsResponse
     */
    private $instance;

    private function __construct(VideoPlaylistAssetsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Playlist Assets Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoPlaylistAssetsResponse());
    }

    /**
     * Sets asset list field.
     *
     * @param AssetList1[]|null $value
     */
    public function assetList(?array $value): self
    {
        $this->instance->setAssetList($value);
        return $this;
    }

    /**
     * Sets has next page field.
     *
     * @param bool|null $value
     */
    public function hasNextPage(?bool $value): self
    {
        $this->instance->setHasNextPage($value);
        return $this;
    }

    /**
     * Sets next page field.
     *
     * @param int|null $value
     */
    public function nextPage(?int $value): self
    {
        $this->instance->setNextPage($value);
        return $this;
    }

    /**
     * Initializes a new Video Playlist Assets Response object.
     */
    public function build(): VideoPlaylistAssetsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
