<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\VideoAssetsMultipartuploadSignResponse;

/**
 * Builder for model VideoAssetsMultipartuploadSignResponse
 *
 * @see VideoAssetsMultipartuploadSignResponse
 */
class VideoAssetsMultipartuploadSignResponseBuilder
{
    /**
     * @var VideoAssetsMultipartuploadSignResponse
     */
    private $instance;

    private function __construct(VideoAssetsMultipartuploadSignResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Assets Multipartupload Sign Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoAssetsMultipartuploadSignResponse());
    }

    /**
     * Sets asset id field.
     *
     * @param string|null $value
     */
    public function assetId(?string $value): self
    {
        $this->instance->setAssetId($value);
        return $this;
    }

    /**
     * Sets part number field.
     *
     * @param string|null $value
     */
    public function partNumber(?string $value): self
    {
        $this->instance->setPartNumber($value);
        return $this;
    }

    /**
     * Sets part upload url field.
     *
     * @param string|null $value
     */
    public function partUploadUrl(?string $value): self
    {
        $this->instance->setPartUploadUrl($value);
        return $this;
    }

    /**
     * Initializes a new Video Assets Multipartupload Sign Response object.
     */
    public function build(): VideoAssetsMultipartuploadSignResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
