<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Aws;
use GumletRestApisLib\Models\ChannelSettings;
use GumletRestApisLib\Models\EmbedDetails;
use GumletRestApisLib\Models\PlayerConfig;
use GumletRestApisLib\Models\VideoProtection;
use GumletRestApisLib\Models\VideoSourcesResponse2;

/**
 * Builder for model VideoSourcesResponse2
 *
 * @see VideoSourcesResponse2
 */
class VideoSourcesResponse2Builder
{
    /**
     * @var VideoSourcesResponse2
     */
    private $instance;

    private function __construct(VideoSourcesResponse2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Sources Response 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new VideoSourcesResponse2());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param string|null $value
     */
    public function createdAt(?string $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets updated at field.
     *
     * @param string|null $value
     */
    public function updatedAt(?string $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Sets video protection field.
     *
     * @param VideoProtection|null $value
     */
    public function videoProtection(?VideoProtection $value): self
    {
        $this->instance->setVideoProtection($value);
        return $this;
    }

    /**
     * Sets player config field.
     *
     * @param PlayerConfig|null $value
     */
    public function playerConfig(?PlayerConfig $value): self
    {
        $this->instance->setPlayerConfig($value);
        return $this;
    }

    /**
     * Sets default profile id field.
     *
     * @param string|null $value
     */
    public function defaultProfileId(?string $value): self
    {
        $this->instance->setDefaultProfileId($value);
        return $this;
    }

    /**
     * Sets insight property id field.
     *
     * @param string|null $value
     */
    public function insightPropertyId(?string $value): self
    {
        $this->instance->setInsightPropertyId($value);
        return $this;
    }

    /**
     * Sets aws field.
     *
     * @param Aws|null $value
     */
    public function aws(?Aws $value): self
    {
        $this->instance->setAws($value);
        return $this;
    }

    /**
     * Sets embed details field.
     *
     * @param EmbedDetails|null $value
     */
    public function embedDetails(?EmbedDetails $value): self
    {
        $this->instance->setEmbedDetails($value);
        return $this;
    }

    /**
     * Sets folders field.
     *
     * @param string[]|null $value
     */
    public function folders(?array $value): self
    {
        $this->instance->setFolders($value);
        return $this;
    }

    /**
     * Sets channel settings field.
     *
     * @param ChannelSettings|null $value
     */
    public function channelSettings(?ChannelSettings $value): self
    {
        $this->instance->setChannelSettings($value);
        return $this;
    }

    /**
     * Initializes a new Video Sources Response 2 object.
     */
    public function build(): VideoSourcesResponse2
    {
        return CoreHelper::clone($this->instance);
    }
}
