<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\VideoLiveAssetsRequest;

/**
 * Builder for model VideoLiveAssetsRequest
 *
 * @see VideoLiveAssetsRequest
 */
class VideoLiveAssetsRequestBuilder
{
    /**
     * @var VideoLiveAssetsRequest
     */
    private $instance;

    private function __construct(VideoLiveAssetsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Video Live Assets Request Builder object.
     *
     * @param string $liveSourceId
     * @param string $resolution
     */
    public static function init(string $liveSourceId, string $resolution): self
    {
        return new self(new VideoLiveAssetsRequest($liveSourceId, $resolution));
    }

    /**
     * Sets title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets mp 4 access field.
     *
     * @param bool|null $value
     */
    public function mp4Access(?bool $value): self
    {
        $this->instance->setMp4Access($value);
        return $this;
    }

    /**
     * Initializes a new Video Live Assets Request object.
     */
    public function build(): VideoLiveAssetsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
