<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\View;

/**
 * Builder for model View
 *
 * @see View
 */
class ViewBuilder
{
    /**
     * @var View
     */
    private $instance;

    private function __construct(View $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new View Builder object.
     */
    public static function init(): self
    {
        return new self(new View());
    }

    /**
     * Sets x field.
     *
     * @param int|null $value
     */
    public function x(?int $value): self
    {
        $this->instance->setX($value);
        return $this;
    }

    /**
     * Sets y field.
     *
     * @param array|null $value
     */
    public function y(?array $value): self
    {
        $this->instance->setY($value);
        return $this;
    }

    /**
     * Sets unit field.
     *
     * @param string|null $value
     */
    public function unit(?string $value): self
    {
        $this->instance->setUnit($value);
        return $this;
    }

    /**
     * Initializes a new View object.
     */
    public function build(): View
    {
        return CoreHelper::clone($this->instance);
    }
}
