<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Webfolder;

/**
 * Builder for model Webfolder
 *
 * @see Webfolder
 */
class WebfolderBuilder
{
    /**
     * @var Webfolder
     */
    private $instance;

    private function __construct(Webfolder $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Webfolder Builder object.
     */
    public static function init(): self
    {
        return new self(new Webfolder());
    }

    /**
     * Sets base url field.
     *
     * @param string|null $value
     */
    public function baseUrl(?string $value): self
    {
        $this->instance->setBaseUrl($value);
        return $this;
    }

    /**
     * Initializes a new Webfolder object.
     */
    public function build(): Webfolder
    {
        return CoreHelper::clone($this->instance);
    }
}
