<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Zoom;

/**
 * Builder for model Zoom
 *
 * @see Zoom
 */
class ZoomBuilder
{
    /**
     * @var Zoom
     */
    private $instance;

    private function __construct(Zoom $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Zoom Builder object.
     *
     * @param string $secret
     */
    public static function init(string $secret): self
    {
        return new self(new Zoom($secret));
    }

    /**
     * Initializes a new Zoom object.
     */
    public function build(): Zoom
    {
        return CoreHelper::clone($this->instance);
    }
}
