<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use GumletRestApisLib\Models\Zoom1;

/**
 * Builder for model Zoom1
 *
 * @see Zoom1
 */
class Zoom1Builder
{
    /**
     * @var Zoom1
     */
    private $instance;

    private function __construct(Zoom1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Zoom 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Zoom1());
    }

    /**
     * Sets secret field.
     *
     * @param string|null $value
     */
    public function secret(?string $value): self
    {
        $this->instance->setSecret($value);
        return $this;
    }

    /**
     * Initializes a new Zoom 1 object.
     */
    public function build(): Zoom1
    {
        return CoreHelper::clone($this->instance);
    }
}
