<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class AllAsset implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $assetId;

    /**
     * @var int|null
     */
    private $progress = 0;

    /**
     * @var int|null
     */
    private $createdAt = 0;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $tag;

    /**
     * @var string|null
     */
    private $sourceId;

    /**
     * @var Input3|null
     */
    private $input;

    /**
     * @var Output|null
     */
    private $output;

    /**
     * Returns Asset Id.
     */
    public function getAssetId(): ?string
    {
        return $this->assetId;
    }

    /**
     * Sets Asset Id.
     *
     * @maps asset_id
     */
    public function setAssetId(?string $assetId): void
    {
        $this->assetId = $assetId;
    }

    /**
     * Returns Progress.
     */
    public function getProgress(): ?int
    {
        return $this->progress;
    }

    /**
     * Sets Progress.
     *
     * @maps progress
     */
    public function setProgress(?int $progress): void
    {
        $this->progress = $progress;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): ?int
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @maps created_at
     */
    public function setCreatedAt(?int $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Tag.
     */
    public function getTag(): ?string
    {
        return $this->tag;
    }

    /**
     * Sets Tag.
     *
     * @maps tag
     */
    public function setTag(?string $tag): void
    {
        $this->tag = $tag;
    }

    /**
     * Returns Source Id.
     */
    public function getSourceId(): ?string
    {
        return $this->sourceId;
    }

    /**
     * Sets Source Id.
     *
     * @maps source_id
     */
    public function setSourceId(?string $sourceId): void
    {
        $this->sourceId = $sourceId;
    }

    /**
     * Returns Input.
     */
    public function getInput(): ?Input3
    {
        return $this->input;
    }

    /**
     * Sets Input.
     *
     * @maps input
     */
    public function setInput(?Input3 $input): void
    {
        $this->input = $input;
    }

    /**
     * Returns Output.
     */
    public function getOutput(): ?Output
    {
        return $this->output;
    }

    /**
     * Sets Output.
     *
     * @maps output
     */
    public function setOutput(?Output $output): void
    {
        $this->output = $output;
    }

    /**
     * Converts the AllAsset object to a human-readable string representation.
     *
     * @return string The string representation of the AllAsset object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AllAsset',
            [
                'assetId' => $this->assetId,
                'progress' => $this->progress,
                'createdAt' => $this->createdAt,
                'status' => $this->status,
                'tag' => $this->tag,
                'sourceId' => $this->sourceId,
                'input' => $this->input,
                'output' => $this->output
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->assetId)) {
            $json['asset_id']   = $this->assetId;
        }
        if (isset($this->progress)) {
            $json['progress']   = $this->progress;
        }
        if (isset($this->createdAt)) {
            $json['created_at'] = $this->createdAt;
        }
        if (isset($this->status)) {
            $json['status']     = $this->status;
        }
        if (isset($this->tag)) {
            $json['tag']        = $this->tag;
        }
        if (isset($this->sourceId)) {
            $json['source_id']  = $this->sourceId;
        }
        if (isset($this->input)) {
            $json['input']      = $this->input;
        }
        if (isset($this->output)) {
            $json['output']     = $this->output;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
