<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class Aws implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $bucketName;

    /**
     * @var string|null
     */
    private $bucketRegion;

    /**
     * @var string|null
     */
    private $accessKey;

    /**
     * @var string|null
     */
    private $secret;

    /**
     * Returns Bucket Name.
     */
    public function getBucketName(): ?string
    {
        return $this->bucketName;
    }

    /**
     * Sets Bucket Name.
     *
     * @maps bucket_name
     */
    public function setBucketName(?string $bucketName): void
    {
        $this->bucketName = $bucketName;
    }

    /**
     * Returns Bucket Region.
     */
    public function getBucketRegion(): ?string
    {
        return $this->bucketRegion;
    }

    /**
     * Sets Bucket Region.
     *
     * @maps bucket_region
     */
    public function setBucketRegion(?string $bucketRegion): void
    {
        $this->bucketRegion = $bucketRegion;
    }

    /**
     * Returns Access Key.
     */
    public function getAccessKey(): ?string
    {
        return $this->accessKey;
    }

    /**
     * Sets Access Key.
     *
     * @maps access_key
     */
    public function setAccessKey(?string $accessKey): void
    {
        $this->accessKey = $accessKey;
    }

    /**
     * Returns Secret.
     */
    public function getSecret(): ?string
    {
        return $this->secret;
    }

    /**
     * Sets Secret.
     *
     * @maps secret
     */
    public function setSecret(?string $secret): void
    {
        $this->secret = $secret;
    }

    /**
     * Converts the Aws object to a human-readable string representation.
     *
     * @return string The string representation of the Aws object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Aws',
            [
                'bucketName' => $this->bucketName,
                'bucketRegion' => $this->bucketRegion,
                'accessKey' => $this->accessKey,
                'secret' => $this->secret
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->bucketName)) {
            $json['bucket_name']   = $this->bucketName;
        }
        if (isset($this->bucketRegion)) {
            $json['bucket_region'] = $this->bucketRegion;
        }
        if (isset($this->accessKey)) {
            $json['access_key']    = $this->accessKey;
        }
        if (isset($this->secret)) {
            $json['secret']        = $this->secret;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
