<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class CallToAction3 implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $startTime = 0;

    /**
     * @var int|null
     */
    private $endTime = 0;

    /**
     * @var string|null
     */
    private $text;

    /**
     * @var string|null
     */
    private $url;

    /**
     * @var string|null
     */
    private $htmlTarget;

    /**
     * Returns Start Time.
     */
    public function getStartTime(): ?int
    {
        return $this->startTime;
    }

    /**
     * Sets Start Time.
     *
     * @maps start_time
     */
    public function setStartTime(?int $startTime): void
    {
        $this->startTime = $startTime;
    }

    /**
     * Returns End Time.
     */
    public function getEndTime(): ?int
    {
        return $this->endTime;
    }

    /**
     * Sets End Time.
     *
     * @maps end_time
     */
    public function setEndTime(?int $endTime): void
    {
        $this->endTime = $endTime;
    }

    /**
     * Returns Text.
     */
    public function getText(): ?string
    {
        return $this->text;
    }

    /**
     * Sets Text.
     *
     * @maps text
     */
    public function setText(?string $text): void
    {
        $this->text = $text;
    }

    /**
     * Returns Url.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Html Target.
     */
    public function getHtmlTarget(): ?string
    {
        return $this->htmlTarget;
    }

    /**
     * Sets Html Target.
     *
     * @maps html_target
     */
    public function setHtmlTarget(?string $htmlTarget): void
    {
        $this->htmlTarget = $htmlTarget;
    }

    /**
     * Converts the CallToAction3 object to a human-readable string representation.
     *
     * @return string The string representation of the CallToAction3 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CallToAction3',
            [
                'startTime' => $this->startTime,
                'endTime' => $this->endTime,
                'text' => $this->text,
                'url' => $this->url,
                'htmlTarget' => $this->htmlTarget
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->startTime)) {
            $json['start_time']  = $this->startTime;
        }
        if (isset($this->endTime)) {
            $json['end_time']    = $this->endTime;
        }
        if (isset($this->text)) {
            $json['text']        = $this->text;
        }
        if (isset($this->url)) {
            $json['url']         = $this->url;
        }
        if (isset($this->htmlTarget)) {
            $json['html_target'] = $this->htmlTarget;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
