<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class Chapter implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $endTime = 0;

    /**
     * @var string|null
     */
    private $label;

    /**
     * Returns End Time.
     */
    public function getEndTime(): ?int
    {
        return $this->endTime;
    }

    /**
     * Sets End Time.
     *
     * @maps endTime
     */
    public function setEndTime(?int $endTime): void
    {
        $this->endTime = $endTime;
    }

    /**
     * Returns Label.
     */
    public function getLabel(): ?string
    {
        return $this->label;
    }

    /**
     * Sets Label.
     *
     * @maps label
     */
    public function setLabel(?string $label): void
    {
        $this->label = $label;
    }

    /**
     * Converts the Chapter object to a human-readable string representation.
     *
     * @return string The string representation of the Chapter object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Chapter', ['endTime' => $this->endTime, 'label' => $this->label]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->endTime)) {
            $json['endTime'] = $this->endTime;
        }
        if (isset($this->label)) {
            $json['label']   = $this->label;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
