<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

/**
 * This is a required field if collection type is cloudinary.
 */
class Cloudinary implements \JsonSerializable
{
    /**
     * @var string
     */
    private $hostName;

    /**
     * @var string
     */
    private $cloudName;

    /**
     * @param string $hostName
     * @param string $cloudName
     */
    public function __construct(string $hostName, string $cloudName)
    {
        $this->hostName = $hostName;
        $this->cloudName = $cloudName;
    }

    /**
     * Returns Host Name.
     */
    public function getHostName(): string
    {
        return $this->hostName;
    }

    /**
     * Sets Host Name.
     *
     * @required
     * @maps host_name
     */
    public function setHostName(string $hostName): void
    {
        $this->hostName = $hostName;
    }

    /**
     * Returns Cloud Name.
     */
    public function getCloudName(): string
    {
        return $this->cloudName;
    }

    /**
     * Sets Cloud Name.
     *
     * @required
     * @maps cloud_name
     */
    public function setCloudName(string $cloudName): void
    {
        $this->cloudName = $cloudName;
    }

    /**
     * Converts the Cloudinary object to a human-readable string representation.
     *
     * @return string The string representation of the Cloudinary object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Cloudinary', ['hostName' => $this->hostName, 'cloudName' => $this->cloudName]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['host_name']  = $this->hostName;
        $json['cloud_name'] = $this->cloudName;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
