<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class Filters implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $collectionId;

    /**
     * Returns Collection Id.
     * The ID of the `collection` you want to filter the data for
     */
    public function getCollectionId(): ?string
    {
        return $this->collectionId;
    }

    /**
     * Sets Collection Id.
     * The ID of the `collection` you want to filter the data for
     *
     * @maps collection_id
     */
    public function setCollectionId(?string $collectionId): void
    {
        $this->collectionId = $collectionId;
    }

    /**
     * Converts the Filters object to a human-readable string representation.
     *
     * @return string The string representation of the Filters object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Filters', ['collectionId' => $this->collectionId]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->collectionId)) {
            $json['collection_id'] = $this->collectionId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
