<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

/**
 * Gumlet allows to generate subtitles from the audio stream (use <a href='https://en.wikipedia.
 * org/wiki/List_of_ISO_639_language_codes'> ISO 639-1 </a> Language Codes)
 */
class GenerateSubtitles implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $audioLanguage;

    /**
     * @var string|null
     */
    private $subtitleLanguages;

    /**
     * Returns Audio Language.
     * Language code for native language of the audio.
     */
    public function getAudioLanguage(): ?string
    {
        return $this->audioLanguage;
    }

    /**
     * Sets Audio Language.
     * Language code for native language of the audio.
     *
     * @maps audio_language
     */
    public function setAudioLanguage(?string $audioLanguage): void
    {
        $this->audioLanguage = $audioLanguage;
    }

    /**
     * Returns Subtitle Languages.
     * Comma separated string of language codes for which subtitle needs to be generated. Maximum four
     * language codes are allowed.
     */
    public function getSubtitleLanguages(): ?string
    {
        return $this->subtitleLanguages;
    }

    /**
     * Sets Subtitle Languages.
     * Comma separated string of language codes for which subtitle needs to be generated. Maximum four
     * language codes are allowed.
     *
     * @maps subtitle_languages
     */
    public function setSubtitleLanguages(?string $subtitleLanguages): void
    {
        $this->subtitleLanguages = $subtitleLanguages;
    }

    /**
     * Converts the GenerateSubtitles object to a human-readable string representation.
     *
     * @return string The string representation of the GenerateSubtitles object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GenerateSubtitles',
            ['audioLanguage' => $this->audioLanguage, 'subtitleLanguages' => $this->subtitleLanguages]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->audioLanguage)) {
            $json['audio_language']     = $this->audioLanguage;
        }
        if (isset($this->subtitleLanguages)) {
            $json['subtitle_languages'] = $this->subtitleLanguages;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
