<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class Input4 implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $resolution;

    /**
     * Returns Resolution.
     *
     * @return string[]|null
     */
    public function getResolution(): ?array
    {
        return $this->resolution;
    }

    /**
     * Sets Resolution.
     *
     * @maps resolution
     *
     * @param string[]|null $resolution
     */
    public function setResolution(?array $resolution): void
    {
        $this->resolution = $resolution;
    }

    /**
     * Converts the Input4 object to a human-readable string representation.
     *
     * @return string The string representation of the Input4 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Input4', ['resolution' => $this->resolution]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->resolution)) {
            $json['resolution'] = $this->resolution;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
