<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class InsightsBreakdownDataRequest implements \JsonSerializable
{
    /**
     * @var Breakdown[]
     */
    private $breakdowns;

    /**
     * @var string
     */
    private $propertyId;

    /**
     * @var Timeframe1
     */
    private $timeframe;

    /**
     * @var Filters1[]|null
     */
    private $filters;

    /**
     * @param Breakdown[] $breakdowns
     * @param string $propertyId
     * @param Timeframe1 $timeframe
     */
    public function __construct(array $breakdowns, string $propertyId, Timeframe1 $timeframe)
    {
        $this->breakdowns = $breakdowns;
        $this->propertyId = $propertyId;
        $this->timeframe = $timeframe;
    }

    /**
     * Returns Breakdowns.
     * Gumlet API supports response for multiple breakdowns in a single API request.
     *
     * @return Breakdown[]
     */
    public function getBreakdowns(): array
    {
        return $this->breakdowns;
    }

    /**
     * Sets Breakdowns.
     * Gumlet API supports response for multiple breakdowns in a single API request.
     *
     * @required
     * @maps breakdowns
     *
     * @param Breakdown[] $breakdowns
     */
    public function setBreakdowns(array $breakdowns): void
    {
        $this->breakdowns = $breakdowns;
    }

    /**
     * Returns Property Id.
     * The five to ten character unique identifier of the Gumlet Insight Property available on the
     * dashboard.
     */
    public function getPropertyId(): string
    {
        return $this->propertyId;
    }

    /**
     * Sets Property Id.
     * The five to ten character unique identifier of the Gumlet Insight Property available on the
     * dashboard.
     *
     * @required
     * @maps property_id
     */
    public function setPropertyId(string $propertyId): void
    {
        $this->propertyId = $propertyId;
    }

    /**
     * Returns Timeframe.
     * The timeframe to get the data for. Currently we only support maximum difference between `start_at`
     * and `end_at` to be *60 days*.
     */
    public function getTimeframe(): Timeframe1
    {
        return $this->timeframe;
    }

    /**
     * Sets Timeframe.
     * The timeframe to get the data for. Currently we only support maximum difference between `start_at`
     * and `end_at` to be *60 days*.
     *
     * @required
     * @maps timeframe
     */
    public function setTimeframe(Timeframe1 $timeframe): void
    {
        $this->timeframe = $timeframe;
    }

    /**
     * Returns Filters.
     * Drill down data in breakdowns with multiple filters, `value` should be an exact match
     *
     * @return Filters1[]|null
     */
    public function getFilters(): ?array
    {
        return $this->filters;
    }

    /**
     * Sets Filters.
     * Drill down data in breakdowns with multiple filters, `value` should be an exact match
     *
     * @maps filters
     *
     * @param Filters1[]|null $filters
     */
    public function setFilters(?array $filters): void
    {
        $this->filters = $filters;
    }

    /**
     * Converts the InsightsBreakdownDataRequest object to a human-readable string representation.
     *
     * @return string The string representation of the InsightsBreakdownDataRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InsightsBreakdownDataRequest',
            [
                'breakdowns' => $this->breakdowns,
                'propertyId' => $this->propertyId,
                'timeframe' => $this->timeframe,
                'filters' => $this->filters
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['breakdowns']  = $this->breakdowns;
        $json['property_id'] = $this->propertyId;
        $json['timeframe']   = $this->timeframe;
        if (isset($this->filters)) {
            $json['filters'] = $this->filters;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
