<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

/**
 * This is a required field if collection type is linode.
 */
class Linode implements \JsonSerializable
{
    /**
     * @var string
     */
    private $bucketName;

    /**
     * @var string
     */
    private $bucketRegion;

    /**
     * @var string
     */
    private $accessKey;

    /**
     * @var string
     */
    private $secret;

    /**
     * @param string $bucketName
     * @param string $bucketRegion
     * @param string $accessKey
     * @param string $secret
     */
    public function __construct(string $bucketName, string $bucketRegion, string $accessKey, string $secret)
    {
        $this->bucketName = $bucketName;
        $this->bucketRegion = $bucketRegion;
        $this->accessKey = $accessKey;
        $this->secret = $secret;
    }

    /**
     * Returns Bucket Name.
     */
    public function getBucketName(): string
    {
        return $this->bucketName;
    }

    /**
     * Sets Bucket Name.
     *
     * @required
     * @maps bucket_name
     */
    public function setBucketName(string $bucketName): void
    {
        $this->bucketName = $bucketName;
    }

    /**
     * Returns Bucket Region.
     */
    public function getBucketRegion(): string
    {
        return $this->bucketRegion;
    }

    /**
     * Sets Bucket Region.
     *
     * @required
     * @maps bucket_region
     */
    public function setBucketRegion(string $bucketRegion): void
    {
        $this->bucketRegion = $bucketRegion;
    }

    /**
     * Returns Access Key.
     */
    public function getAccessKey(): string
    {
        return $this->accessKey;
    }

    /**
     * Sets Access Key.
     *
     * @required
     * @maps access_key
     */
    public function setAccessKey(string $accessKey): void
    {
        $this->accessKey = $accessKey;
    }

    /**
     * Returns Secret.
     */
    public function getSecret(): string
    {
        return $this->secret;
    }

    /**
     * Sets Secret.
     *
     * @required
     * @maps secret
     */
    public function setSecret(string $secret): void
    {
        $this->secret = $secret;
    }

    /**
     * Converts the Linode object to a human-readable string representation.
     *
     * @return string The string representation of the Linode object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Linode',
            [
                'bucketName' => $this->bucketName,
                'bucketRegion' => $this->bucketRegion,
                'accessKey' => $this->accessKey,
                'secret' => $this->secret
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['bucket_name']   = $this->bucketName;
        $json['bucket_region'] = $this->bucketRegion;
        $json['access_key']    = $this->accessKey;
        $json['secret']        = $this->secret;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
