<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class OrgWebhooksRequest1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $url;

    /**
     * @var string|null
     */
    private $secretToken;

    /**
     * @var string|null
     */
    private $triggers;

    /**
     * @var string|null
     */
    private $sources;

    /**
     * Returns Url.
     * URL from the application you want to send data to.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * URL from the application you want to send data to.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Secret Token.
     * Authentication token to ensure legitimacy of Gumlet Webhook request on your application.
     */
    public function getSecretToken(): ?string
    {
        return $this->secretToken;
    }

    /**
     * Sets Secret Token.
     * Authentication token to ensure legitimacy of Gumlet Webhook request on your application.
     *
     * @maps secret_token
     */
    public function setSecretToken(?string $secretToken): void
    {
        $this->secretToken = $secretToken;
    }

    /**
     * Returns Triggers.
     * Triggers for the invocation of webhookos, supported option is `status`.
     */
    public function getTriggers(): ?string
    {
        return $this->triggers;
    }

    /**
     * Sets Triggers.
     * Triggers for the invocation of webhookos, supported option is `status`.
     *
     * @maps triggers
     */
    public function setTriggers(?string $triggers): void
    {
        $this->triggers = $triggers;
    }

    /**
     * Returns Sources.
     * List of video collection identifiers for which webhooks are needed to be invoked.
     */
    public function getSources(): ?string
    {
        return $this->sources;
    }

    /**
     * Sets Sources.
     * List of video collection identifiers for which webhooks are needed to be invoked.
     *
     * @maps sources
     */
    public function setSources(?string $sources): void
    {
        $this->sources = $sources;
    }

    /**
     * Converts the OrgWebhooksRequest1 object to a human-readable string representation.
     *
     * @return string The string representation of the OrgWebhooksRequest1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OrgWebhooksRequest1',
            [
                'url' => $this->url,
                'secretToken' => $this->secretToken,
                'triggers' => $this->triggers,
                'sources' => $this->sources
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->url)) {
            $json['url']          = $this->url;
        }
        if (isset($this->secretToken)) {
            $json['secret_token'] = $this->secretToken;
        }
        if (isset($this->triggers)) {
            $json['triggers']     = $this->triggers;
        }
        if (isset($this->sources)) {
            $json['sources']      = $this->sources;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
