<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class OrgWebhooksRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $url;

    /**
     * @var string
     */
    private $secretToken;

    /**
     * @var string[]
     */
    private $triggers;

    /**
     * @var string[]
     */
    private $sources;

    /**
     * @param string $url
     * @param string $secretToken
     * @param string[] $triggers
     * @param string[] $sources
     */
    public function __construct(string $url, string $secretToken, array $triggers, array $sources)
    {
        $this->url = $url;
        $this->secretToken = $secretToken;
        $this->triggers = $triggers;
        $this->sources = $sources;
    }

    /**
     * Returns Url.
     * URL from the application you want to send data to.
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * URL from the application you want to send data to.
     *
     * @required
     * @maps url
     */
    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Secret Token.
     * Authentication token to ensure legitimacy of Gumlet Webhook request on your application.
     */
    public function getSecretToken(): string
    {
        return $this->secretToken;
    }

    /**
     * Sets Secret Token.
     * Authentication token to ensure legitimacy of Gumlet Webhook request on your application.
     *
     * @required
     * @maps secret_token
     */
    public function setSecretToken(string $secretToken): void
    {
        $this->secretToken = $secretToken;
    }

    /**
     * Returns Triggers.
     * Triggers for the invocation of webhookos, supported option is `status`.
     *
     * @return string[]
     */
    public function getTriggers(): array
    {
        return $this->triggers;
    }

    /**
     * Sets Triggers.
     * Triggers for the invocation of webhookos, supported option is `status`.
     *
     * @required
     * @maps triggers
     *
     * @param string[] $triggers
     */
    public function setTriggers(array $triggers): void
    {
        $this->triggers = $triggers;
    }

    /**
     * Returns Sources.
     * List of video collection identifiers for which webhooks are needed to be invoked.
     *
     * @return string[]
     */
    public function getSources(): array
    {
        return $this->sources;
    }

    /**
     * Sets Sources.
     * List of video collection identifiers for which webhooks are needed to be invoked.
     *
     * @required
     * @maps sources
     *
     * @param string[] $sources
     */
    public function setSources(array $sources): void
    {
        $this->sources = $sources;
    }

    /**
     * Converts the OrgWebhooksRequest object to a human-readable string representation.
     *
     * @return string The string representation of the OrgWebhooksRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OrgWebhooksRequest',
            [
                'url' => $this->url,
                'secretToken' => $this->secretToken,
                'triggers' => $this->triggers,
                'sources' => $this->sources
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['url']          = $this->url;
        $json['secret_token'] = $this->secretToken;
        $json['triggers']     = $this->triggers;
        $json['sources']      = $this->sources;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
