<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class Output4 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $playbackUrl;

    /**
     * Returns Playback Url.
     */
    public function getPlaybackUrl(): ?string
    {
        return $this->playbackUrl;
    }

    /**
     * Sets Playback Url.
     *
     * @maps playback_url
     */
    public function setPlaybackUrl(?string $playbackUrl): void
    {
        $this->playbackUrl = $playbackUrl;
    }

    /**
     * Converts the Output4 object to a human-readable string representation.
     *
     * @return string The string representation of the Output4 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Output4', ['playbackUrl' => $this->playbackUrl]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->playbackUrl)) {
            $json['playback_url'] = $this->playbackUrl;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
