<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

/**
 * This is a required field if collection type is proxy.
 */
class Proxy implements \JsonSerializable
{
    /**
     * @var string
     */
    private $whitelistedDomains;

    /**
     * @param string $whitelistedDomains
     */
    public function __construct(string $whitelistedDomains)
    {
        $this->whitelistedDomains = $whitelistedDomains;
    }

    /**
     * Returns Whitelisted Domains.
     */
    public function getWhitelistedDomains(): string
    {
        return $this->whitelistedDomains;
    }

    /**
     * Sets Whitelisted Domains.
     *
     * @required
     * @maps whitelisted_domains
     */
    public function setWhitelistedDomains(string $whitelistedDomains): void
    {
        $this->whitelistedDomains = $whitelistedDomains;
    }

    /**
     * Converts the Proxy object to a human-readable string representation.
     *
     * @return string The string representation of the Proxy object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Proxy', ['whitelistedDomains' => $this->whitelistedDomains]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['whitelisted_domains'] = $this->whitelistedDomains;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
