<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

/**
 * Gumlet provides multiple options for securing your video playback.
 */
class VideoProtection1 implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $signedUrl = false;

    /**
     * @var string|null
     */
    private $signedUrlSecret;

    /**
     * @var string[]|null
     */
    private $blacklistedCountries;

    /**
     * @var string|null
     */
    private $whitelistedReferrers;

    /**
     * Returns Signed Url.
     */
    public function getSignedUrl(): ?bool
    {
        return $this->signedUrl;
    }

    /**
     * Sets Signed Url.
     *
     * @maps signed_url
     */
    public function setSignedUrl(?bool $signedUrl): void
    {
        $this->signedUrl = $signedUrl;
    }

    /**
     * Returns Signed Url Secret.
     */
    public function getSignedUrlSecret(): ?string
    {
        return $this->signedUrlSecret;
    }

    /**
     * Sets Signed Url Secret.
     *
     * @maps signed_url_secret
     */
    public function setSignedUrlSecret(?string $signedUrlSecret): void
    {
        $this->signedUrlSecret = $signedUrlSecret;
    }

    /**
     * Returns Blacklisted Countries.
     * Example: ["IN","USA"]
     *
     * @return string[]|null
     */
    public function getBlacklistedCountries(): ?array
    {
        return $this->blacklistedCountries;
    }

    /**
     * Sets Blacklisted Countries.
     * Example: ["IN","USA"]
     *
     * @maps blacklisted_countries
     *
     * @param string[]|null $blacklistedCountries
     */
    public function setBlacklistedCountries(?array $blacklistedCountries): void
    {
        $this->blacklistedCountries = $blacklistedCountries;
    }

    /**
     * Returns Whitelisted Referrers.
     */
    public function getWhitelistedReferrers(): ?string
    {
        return $this->whitelistedReferrers;
    }

    /**
     * Sets Whitelisted Referrers.
     *
     * @maps whitelisted_referrers
     */
    public function setWhitelistedReferrers(?string $whitelistedReferrers): void
    {
        $this->whitelistedReferrers = $whitelistedReferrers;
    }

    /**
     * Converts the VideoProtection1 object to a human-readable string representation.
     *
     * @return string The string representation of the VideoProtection1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VideoProtection1',
            [
                'signedUrl' => $this->signedUrl,
                'signedUrlSecret' => $this->signedUrlSecret,
                'blacklistedCountries' => $this->blacklistedCountries,
                'whitelistedReferrers' => $this->whitelistedReferrers
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->signedUrl)) {
            $json['signed_url']            = $this->signedUrl;
        }
        if (isset($this->signedUrlSecret)) {
            $json['signed_url_secret']     = $this->signedUrlSecret;
        }
        if (isset($this->blacklistedCountries)) {
            $json['blacklisted_countries'] = $this->blacklistedCountries;
        }
        if (isset($this->whitelistedReferrers)) {
            $json['whitelisted_referrers'] = $this->whitelistedReferrers;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
