<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class VideoLiveAssetsUpdateRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $liveAssetId;

    /**
     * @var string|null
     */
    private $title;

    /**
     * @param string $liveAssetId
     */
    public function __construct(string $liveAssetId)
    {
        $this->liveAssetId = $liveAssetId;
    }

    /**
     * Returns Live Asset Id.
     * Gumlet live video asset id.
     */
    public function getLiveAssetId(): string
    {
        return $this->liveAssetId;
    }

    /**
     * Sets Live Asset Id.
     * Gumlet live video asset id.
     *
     * @required
     * @maps live_asset_id
     */
    public function setLiveAssetId(string $liveAssetId): void
    {
        $this->liveAssetId = $liveAssetId;
    }

    /**
     * Returns Title.
     * Your live stream asset title
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     * Your live stream asset title
     *
     * @maps title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * Converts the VideoLiveAssetsUpdateRequest object to a human-readable string representation.
     *
     * @return string The string representation of the VideoLiveAssetsUpdateRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VideoLiveAssetsUpdateRequest',
            ['liveAssetId' => $this->liveAssetId, 'title' => $this->title]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['live_asset_id'] = $this->liveAssetId;
        if (isset($this->title)) {
            $json['title']     = $this->title;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
