<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class VideoProtection implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $signedUrl = true;

    /**
     * @var string|null
     */
    private $signedUrlSecret;

    /**
     * Returns Signed Url.
     */
    public function getSignedUrl(): ?bool
    {
        return $this->signedUrl;
    }

    /**
     * Sets Signed Url.
     *
     * @maps signed_url
     */
    public function setSignedUrl(?bool $signedUrl): void
    {
        $this->signedUrl = $signedUrl;
    }

    /**
     * Returns Signed Url Secret.
     */
    public function getSignedUrlSecret(): ?string
    {
        return $this->signedUrlSecret;
    }

    /**
     * Sets Signed Url Secret.
     *
     * @maps signed_url_secret
     */
    public function setSignedUrlSecret(?string $signedUrlSecret): void
    {
        $this->signedUrlSecret = $signedUrlSecret;
    }

    /**
     * Converts the VideoProtection object to a human-readable string representation.
     *
     * @return string The string representation of the VideoProtection object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VideoProtection',
            ['signedUrl' => $this->signedUrl, 'signedUrlSecret' => $this->signedUrlSecret]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->signedUrl)) {
            $json['signed_url']        = $this->signedUrl;
        }
        if (isset($this->signedUrlSecret)) {
            $json['signed_url_secret'] = $this->signedUrlSecret;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
