<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class VideoAssetsSubtitleUploadEventRequest implements \JsonSerializable
{
    /**
     * @var UploadResponse[]|null
     */
    private $uploadResponses;

    /**
     * Returns Upload Responses.
     *
     * @return UploadResponse[]|null
     */
    public function getUploadResponses(): ?array
    {
        return $this->uploadResponses;
    }

    /**
     * Sets Upload Responses.
     *
     * @maps upload_responses
     *
     * @param UploadResponse[]|null $uploadResponses
     */
    public function setUploadResponses(?array $uploadResponses): void
    {
        $this->uploadResponses = $uploadResponses;
    }

    /**
     * Converts the VideoAssetsSubtitleUploadEventRequest object to a human-readable string representation.
     *
     * @return string The string representation of the VideoAssetsSubtitleUploadEventRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VideoAssetsSubtitleUploadEventRequest',
            ['uploadResponses' => $this->uploadResponses]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->uploadResponses)) {
            $json['upload_responses'] = $this->uploadResponses;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
