<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class VideoSourcesRequest1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $defaultProfileId;

    /**
     * @var string[]|null
     */
    private $tempCname;

    /**
     * @var string|null
     */
    private $insightPropertyId;

    /**
     * @var PlayerConfig2|null
     */
    private $playerConfig;

    /**
     * @var VideoProtection1|null
     */
    private $videoProtection;

    /**
     * @var ChannelSettings2|null
     */
    private $channelSettings;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var Webfolder|null
     */
    private $webfolder;

    /**
     * @var Aws1|null
     */
    private $aws;

    /**
     * @var Proxy|null
     */
    private $proxy;

    /**
     * @var Gcs|null
     */
    private $gcs;

    /**
     * @var Dostorage|null
     */
    private $dostorage;

    /**
     * @var Wasabi|null
     */
    private $wasabi;

    /**
     * @var Linode|null
     */
    private $linode;

    /**
     * @var Backblaze|null
     */
    private $backblaze;

    /**
     * @var Cloudflare|null
     */
    private $cloudflare;

    /**
     * @var Cloudinary|null
     */
    private $cloudinary;

    /**
     * @var Azure|null
     */
    private $azure;

    /**
     * @var Zoom|null
     */
    private $zoom;

    /**
     * Returns Name.
     * video collection name
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * video collection name
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Default Profile Id.
     * Gumlet provides the functionality of creating multiple video assets using the same set of parameters.
     */
    public function getDefaultProfileId(): ?string
    {
        return $this->defaultProfileId;
    }

    /**
     * Sets Default Profile Id.
     * Gumlet provides the functionality of creating multiple video assets using the same set of parameters.
     *
     * @maps default_profile_id
     */
    public function setDefaultProfileId(?string $defaultProfileId): void
    {
        $this->defaultProfileId = $defaultProfileId;
    }

    /**
     * Returns Temp Cname.
     * cname for channel
     *
     * @return string[]|null
     */
    public function getTempCname(): ?array
    {
        return $this->tempCname;
    }

    /**
     * Sets Temp Cname.
     * cname for channel
     *
     * @maps temp_cname
     *
     * @param string[]|null $tempCname
     */
    public function setTempCname(?array $tempCname): void
    {
        $this->tempCname = $tempCname;
    }

    /**
     * Returns Insight Property Id.
     * The five to ten character unique identifier of the Gumlet Insight Property available on the
     * dashboard.
     */
    public function getInsightPropertyId(): ?string
    {
        return $this->insightPropertyId;
    }

    /**
     * Sets Insight Property Id.
     * The five to ten character unique identifier of the Gumlet Insight Property available on the
     * dashboard.
     *
     * @maps insight_property_id
     */
    public function setInsightPropertyId(?string $insightPropertyId): void
    {
        $this->insightPropertyId = $insightPropertyId;
    }

    /**
     * Returns Player Config.
     * Configure player settings for this playlist, it overrides the setting set on collection.
     */
    public function getPlayerConfig(): ?PlayerConfig2
    {
        return $this->playerConfig;
    }

    /**
     * Sets Player Config.
     * Configure player settings for this playlist, it overrides the setting set on collection.
     *
     * @maps player_config
     */
    public function setPlayerConfig(?PlayerConfig2 $playerConfig): void
    {
        $this->playerConfig = $playerConfig;
    }

    /**
     * Returns Video Protection.
     * Gumlet provides multiple options for securing your video playback.
     */
    public function getVideoProtection(): ?VideoProtection1
    {
        return $this->videoProtection;
    }

    /**
     * Sets Video Protection.
     * Gumlet provides multiple options for securing your video playback.
     *
     * @maps video_protection
     */
    public function setVideoProtection(?VideoProtection1 $videoProtection): void
    {
        $this->videoProtection = $videoProtection;
    }

    /**
     * Returns Channel Settings.
     * Configurations to set various channel settings.
     */
    public function getChannelSettings(): ?ChannelSettings2
    {
        return $this->channelSettings;
    }

    /**
     * Sets Channel Settings.
     * Configurations to set various channel settings.
     *
     * @maps channel_settings
     */
    public function setChannelSettings(?ChannelSettings2 $channelSettings): void
    {
        $this->channelSettings = $channelSettings;
    }

    /**
     * Returns Type.
     * Video collections are top-level entities in Gumlet. You can use them to organize videos for
     * different teams/departments or use cases.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Video collections are top-level entities in Gumlet. You can use them to organize videos for
     * different teams/departments or use cases.
     *
     * @maps type
     * @factory \GumletRestApisLib\Models\TypeEnum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Webfolder.
     * This is a required field if collection type is webfolder.
     */
    public function getWebfolder(): ?Webfolder
    {
        return $this->webfolder;
    }

    /**
     * Sets Webfolder.
     * This is a required field if collection type is webfolder.
     *
     * @maps webfolder
     */
    public function setWebfolder(?Webfolder $webfolder): void
    {
        $this->webfolder = $webfolder;
    }

    /**
     * Returns Aws.
     * This is a required field if collection type is aws.
     */
    public function getAws(): ?Aws1
    {
        return $this->aws;
    }

    /**
     * Sets Aws.
     * This is a required field if collection type is aws.
     *
     * @maps aws
     */
    public function setAws(?Aws1 $aws): void
    {
        $this->aws = $aws;
    }

    /**
     * Returns Proxy.
     * This is a required field if collection type is proxy.
     */
    public function getProxy(): ?Proxy
    {
        return $this->proxy;
    }

    /**
     * Sets Proxy.
     * This is a required field if collection type is proxy.
     *
     * @maps proxy
     */
    public function setProxy(?Proxy $proxy): void
    {
        $this->proxy = $proxy;
    }

    /**
     * Returns Gcs.
     * This is a required field if collection type is gcs.
     */
    public function getGcs(): ?Gcs
    {
        return $this->gcs;
    }

    /**
     * Sets Gcs.
     * This is a required field if collection type is gcs.
     *
     * @maps gcs
     */
    public function setGcs(?Gcs $gcs): void
    {
        $this->gcs = $gcs;
    }

    /**
     * Returns Dostorage.
     * This is a required field if collection type is dostorage.
     */
    public function getDostorage(): ?Dostorage
    {
        return $this->dostorage;
    }

    /**
     * Sets Dostorage.
     * This is a required field if collection type is dostorage.
     *
     * @maps dostorage
     */
    public function setDostorage(?Dostorage $dostorage): void
    {
        $this->dostorage = $dostorage;
    }

    /**
     * Returns Wasabi.
     * This is a required field if collection type is wasabi.
     */
    public function getWasabi(): ?Wasabi
    {
        return $this->wasabi;
    }

    /**
     * Sets Wasabi.
     * This is a required field if collection type is wasabi.
     *
     * @maps wasabi
     */
    public function setWasabi(?Wasabi $wasabi): void
    {
        $this->wasabi = $wasabi;
    }

    /**
     * Returns Linode.
     * This is a required field if collection type is linode.
     */
    public function getLinode(): ?Linode
    {
        return $this->linode;
    }

    /**
     * Sets Linode.
     * This is a required field if collection type is linode.
     *
     * @maps linode
     */
    public function setLinode(?Linode $linode): void
    {
        $this->linode = $linode;
    }

    /**
     * Returns Backblaze.
     * This is a required field if collection type is backblaze.
     */
    public function getBackblaze(): ?Backblaze
    {
        return $this->backblaze;
    }

    /**
     * Sets Backblaze.
     * This is a required field if collection type is backblaze.
     *
     * @maps backblaze
     */
    public function setBackblaze(?Backblaze $backblaze): void
    {
        $this->backblaze = $backblaze;
    }

    /**
     * Returns Cloudflare.
     * This is a required field if collection type is cloudflare.
     */
    public function getCloudflare(): ?Cloudflare
    {
        return $this->cloudflare;
    }

    /**
     * Sets Cloudflare.
     * This is a required field if collection type is cloudflare.
     *
     * @maps cloudflare
     */
    public function setCloudflare(?Cloudflare $cloudflare): void
    {
        $this->cloudflare = $cloudflare;
    }

    /**
     * Returns Cloudinary.
     * This is a required field if collection type is cloudinary.
     */
    public function getCloudinary(): ?Cloudinary
    {
        return $this->cloudinary;
    }

    /**
     * Sets Cloudinary.
     * This is a required field if collection type is cloudinary.
     *
     * @maps cloudinary
     */
    public function setCloudinary(?Cloudinary $cloudinary): void
    {
        $this->cloudinary = $cloudinary;
    }

    /**
     * Returns Azure.
     * This is a required field if collection type is azure.
     */
    public function getAzure(): ?Azure
    {
        return $this->azure;
    }

    /**
     * Sets Azure.
     * This is a required field if collection type is azure.
     *
     * @maps azure
     */
    public function setAzure(?Azure $azure): void
    {
        $this->azure = $azure;
    }

    /**
     * Returns Zoom.
     * This is a required field if collection type is zoom.
     */
    public function getZoom(): ?Zoom
    {
        return $this->zoom;
    }

    /**
     * Sets Zoom.
     * This is a required field if collection type is zoom.
     *
     * @maps zoom
     */
    public function setZoom(?Zoom $zoom): void
    {
        $this->zoom = $zoom;
    }

    /**
     * Converts the VideoSourcesRequest1 object to a human-readable string representation.
     *
     * @return string The string representation of the VideoSourcesRequest1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VideoSourcesRequest1',
            [
                'name' => $this->name,
                'defaultProfileId' => $this->defaultProfileId,
                'tempCname' => $this->tempCname,
                'insightPropertyId' => $this->insightPropertyId,
                'playerConfig' => $this->playerConfig,
                'videoProtection' => $this->videoProtection,
                'channelSettings' => $this->channelSettings,
                'type' => $this->type,
                'webfolder' => $this->webfolder,
                'aws' => $this->aws,
                'proxy' => $this->proxy,
                'gcs' => $this->gcs,
                'dostorage' => $this->dostorage,
                'wasabi' => $this->wasabi,
                'linode' => $this->linode,
                'backblaze' => $this->backblaze,
                'cloudflare' => $this->cloudflare,
                'cloudinary' => $this->cloudinary,
                'azure' => $this->azure,
                'zoom' => $this->zoom
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']                = $this->name;
        }
        if (isset($this->defaultProfileId)) {
            $json['default_profile_id']  = $this->defaultProfileId;
        }
        if (isset($this->tempCname)) {
            $json['temp_cname']          = $this->tempCname;
        }
        if (isset($this->insightPropertyId)) {
            $json['insight_property_id'] = $this->insightPropertyId;
        }
        if (isset($this->playerConfig)) {
            $json['player_config']       = $this->playerConfig;
        }
        if (isset($this->videoProtection)) {
            $json['video_protection']    = $this->videoProtection;
        }
        if (isset($this->channelSettings)) {
            $json['channel_settings']    = $this->channelSettings;
        }
        if (isset($this->type)) {
            $json['type']                = TypeEnum::checkValue($this->type);
        }
        if (isset($this->webfolder)) {
            $json['webfolder']           = $this->webfolder;
        }
        if (isset($this->aws)) {
            $json['aws']                 = $this->aws;
        }
        if (isset($this->proxy)) {
            $json['proxy']               = $this->proxy;
        }
        if (isset($this->gcs)) {
            $json['gcs']                 = $this->gcs;
        }
        if (isset($this->dostorage)) {
            $json['dostorage']           = $this->dostorage;
        }
        if (isset($this->wasabi)) {
            $json['wasabi']              = $this->wasabi;
        }
        if (isset($this->linode)) {
            $json['linode']              = $this->linode;
        }
        if (isset($this->backblaze)) {
            $json['backblaze']           = $this->backblaze;
        }
        if (isset($this->cloudflare)) {
            $json['cloudflare']          = $this->cloudflare;
        }
        if (isset($this->cloudinary)) {
            $json['cloudinary']          = $this->cloudinary;
        }
        if (isset($this->azure)) {
            $json['azure']               = $this->azure;
        }
        if (isset($this->zoom)) {
            $json['zoom']                = $this->zoom;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
