<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class VideoLiveAssetsListResponse implements \JsonSerializable
{
    /**
     * @var AllLiveAsset[]|null
     */
    private $allLiveAssets;

    /**
     * @var int|null
     */
    private $totalLiveAssetCount = 0;

    /**
     * @var int|null
     */
    private $currentOffset = 0;

    /**
     * Returns All Live Assets.
     *
     * @return AllLiveAsset[]|null
     */
    public function getAllLiveAssets(): ?array
    {
        return $this->allLiveAssets;
    }

    /**
     * Sets All Live Assets.
     *
     * @maps all_live_assets
     *
     * @param AllLiveAsset[]|null $allLiveAssets
     */
    public function setAllLiveAssets(?array $allLiveAssets): void
    {
        $this->allLiveAssets = $allLiveAssets;
    }

    /**
     * Returns Total Live Asset Count.
     */
    public function getTotalLiveAssetCount(): ?int
    {
        return $this->totalLiveAssetCount;
    }

    /**
     * Sets Total Live Asset Count.
     *
     * @maps total_live_asset_count
     */
    public function setTotalLiveAssetCount(?int $totalLiveAssetCount): void
    {
        $this->totalLiveAssetCount = $totalLiveAssetCount;
    }

    /**
     * Returns Current Offset.
     */
    public function getCurrentOffset(): ?int
    {
        return $this->currentOffset;
    }

    /**
     * Sets Current Offset.
     *
     * @maps current_offset
     */
    public function setCurrentOffset(?int $currentOffset): void
    {
        $this->currentOffset = $currentOffset;
    }

    /**
     * Converts the VideoLiveAssetsListResponse object to a human-readable string representation.
     *
     * @return string The string representation of the VideoLiveAssetsListResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VideoLiveAssetsListResponse',
            [
                'allLiveAssets' => $this->allLiveAssets,
                'totalLiveAssetCount' => $this->totalLiveAssetCount,
                'currentOffset' => $this->currentOffset
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->allLiveAssets)) {
            $json['all_live_assets']        = $this->allLiveAssets;
        }
        if (isset($this->totalLiveAssetCount)) {
            $json['total_live_asset_count'] = $this->totalLiveAssetCount;
        }
        if (isset($this->currentOffset)) {
            $json['current_offset']         = $this->currentOffset;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
