<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class VideoStreamingDurationResponse implements \JsonSerializable
{
    /**
     * @var Datum[]|null
     */
    private $data;

    /**
     * @var bool|null
     */
    private $hasNextPage = true;

    /**
     * Returns Data.
     *
     * @return Datum[]|null
     */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * Sets Data.
     *
     * @maps data
     *
     * @param Datum[]|null $data
     */
    public function setData(?array $data): void
    {
        $this->data = $data;
    }

    /**
     * Returns Has Next Page.
     */
    public function getHasNextPage(): ?bool
    {
        return $this->hasNextPage;
    }

    /**
     * Sets Has Next Page.
     *
     * @maps has_next_page
     */
    public function setHasNextPage(?bool $hasNextPage): void
    {
        $this->hasNextPage = $hasNextPage;
    }

    /**
     * Converts the VideoStreamingDurationResponse object to a human-readable string representation.
     *
     * @return string The string representation of the VideoStreamingDurationResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VideoStreamingDurationResponse',
            ['data' => $this->data, 'hasNextPage' => $this->hasNextPage]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->data)) {
            $json['data']          = $this->data;
        }
        if (isset($this->hasNextPage)) {
            $json['has_next_page'] = $this->hasNextPage;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
