<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class VideoAssetsThumbnailRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $frameAtSecond;

    /**
     * @param int $frameAtSecond
     */
    public function __construct(int $frameAtSecond)
    {
        $this->frameAtSecond = $frameAtSecond;
    }

    /**
     * Returns Frame at Second.
     * Frame secound
     */
    public function getFrameAtSecond(): int
    {
        return $this->frameAtSecond;
    }

    /**
     * Sets Frame at Second.
     * Frame secound
     *
     * @required
     * @maps frame_at_second
     */
    public function setFrameAtSecond(int $frameAtSecond): void
    {
        $this->frameAtSecond = $frameAtSecond;
    }

    /**
     * Converts the VideoAssetsThumbnailRequest object to a human-readable string representation.
     *
     * @return string The string representation of the VideoAssetsThumbnailRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('VideoAssetsThumbnailRequest', ['frameAtSecond' => $this->frameAtSecond]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['frame_at_second'] = $this->frameAtSecond;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
