<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class VideoAssetsSubtitleUploadRequest implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $languageCodes;

    /**
     * Returns Language Codes.
     * List of language Code to upload subtitle file  (use <a href='https://en.wikipedia.
     * org/wiki/List_of_ISO_639_language_codes'> ISO 639-1 </a> Language Codes)
     *
     * @return string[]|null
     */
    public function getLanguageCodes(): ?array
    {
        return $this->languageCodes;
    }

    /**
     * Sets Language Codes.
     * List of language Code to upload subtitle file  (use <a href='https://en.wikipedia.
     * org/wiki/List_of_ISO_639_language_codes'> ISO 639-1 </a> Language Codes)
     *
     * @maps language_codes
     *
     * @param string[]|null $languageCodes
     */
    public function setLanguageCodes(?array $languageCodes): void
    {
        $this->languageCodes = $languageCodes;
    }

    /**
     * Converts the VideoAssetsSubtitleUploadRequest object to a human-readable string representation.
     *
     * @return string The string representation of the VideoAssetsSubtitleUploadRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('VideoAssetsSubtitleUploadRequest', ['languageCodes' => $this->languageCodes]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->languageCodes)) {
            $json['language_codes'] = $this->languageCodes;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
