<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class VideoPlaylistAssetRequest implements \JsonSerializable
{
    /**
     * @var AssetList[]
     */
    private $assetList;

    /**
     * @param AssetList[] $assetList
     */
    public function __construct(array $assetList)
    {
        $this->assetList = $assetList;
    }

    /**
     * Returns Asset List.
     *
     * @return AssetList[]
     */
    public function getAssetList(): array
    {
        return $this->assetList;
    }

    /**
     * Sets Asset List.
     *
     * @required
     * @maps asset_list
     *
     * @param AssetList[] $assetList
     */
    public function setAssetList(array $assetList): void
    {
        $this->assetList = $assetList;
    }

    /**
     * Converts the VideoPlaylistAssetRequest object to a human-readable string representation.
     *
     * @return string The string representation of the VideoPlaylistAssetRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('VideoPlaylistAssetRequest', ['assetList' => $this->assetList]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['asset_list'] = $this->assetList;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
