<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class Video implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $fileName;

    /**
     * @var int|null
     */
    private $size = 0;

    /**
     * @var string|null
     */
    private $resolution;

    /**
     * @var int|null
     */
    private $duration = 0;

    /**
     * Returns File Name.
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * Sets File Name.
     *
     * @maps fileName
     */
    public function setFileName(?string $fileName): void
    {
        $this->fileName = $fileName;
    }

    /**
     * Returns Size.
     */
    public function getSize(): ?int
    {
        return $this->size;
    }

    /**
     * Sets Size.
     *
     * @maps size
     */
    public function setSize(?int $size): void
    {
        $this->size = $size;
    }

    /**
     * Returns Resolution.
     */
    public function getResolution(): ?string
    {
        return $this->resolution;
    }

    /**
     * Sets Resolution.
     *
     * @maps resolution
     */
    public function setResolution(?string $resolution): void
    {
        $this->resolution = $resolution;
    }

    /**
     * Returns Duration.
     */
    public function getDuration(): ?int
    {
        return $this->duration;
    }

    /**
     * Sets Duration.
     *
     * @maps duration
     */
    public function setDuration(?int $duration): void
    {
        $this->duration = $duration;
    }

    /**
     * Converts the Video object to a human-readable string representation.
     *
     * @return string The string representation of the Video object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Video',
            [
                'fileName' => $this->fileName,
                'size' => $this->size,
                'resolution' => $this->resolution,
                'duration' => $this->duration
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->fileName)) {
            $json['fileName']   = $this->fileName;
        }
        if (isset($this->size)) {
            $json['size']       = $this->size;
        }
        if (isset($this->resolution)) {
            $json['resolution'] = $this->resolution;
        }
        if (isset($this->duration)) {
            $json['duration']   = $this->duration;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
