<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class Views implements \JsonSerializable
{
    /**
     * @var Datum1[]|null
     */
    private $data;

    /**
     * @var bool|null
     */
    private $hasNextPage = true;

    /**
     * @var int|null
     */
    private $currentPage = 0;

    /**
     * Returns Data.
     *
     * @return Datum1[]|null
     */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * Sets Data.
     *
     * @maps data
     *
     * @param Datum1[]|null $data
     */
    public function setData(?array $data): void
    {
        $this->data = $data;
    }

    /**
     * Returns Has Next Page.
     */
    public function getHasNextPage(): ?bool
    {
        return $this->hasNextPage;
    }

    /**
     * Sets Has Next Page.
     *
     * @maps has_next_page
     */
    public function setHasNextPage(?bool $hasNextPage): void
    {
        $this->hasNextPage = $hasNextPage;
    }

    /**
     * Returns Current Page.
     */
    public function getCurrentPage(): ?int
    {
        return $this->currentPage;
    }

    /**
     * Sets Current Page.
     *
     * @maps current_page
     */
    public function setCurrentPage(?int $currentPage): void
    {
        $this->currentPage = $currentPage;
    }

    /**
     * Converts the Views object to a human-readable string representation.
     *
     * @return string The string representation of the Views object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Views',
            ['data' => $this->data, 'hasNextPage' => $this->hasNextPage, 'currentPage' => $this->currentPage]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->data)) {
            $json['data']          = $this->data;
        }
        if (isset($this->hasNextPage)) {
            $json['has_next_page'] = $this->hasNextPage;
        }
        if (isset($this->currentPage)) {
            $json['current_page']  = $this->currentPage;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
