<?php

declare(strict_types=1);

/*
 * GumletRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GumletRestApisLib\Models;

use GumletRestApisLib\ApiHelper;
use stdClass;

class Views1 implements \JsonSerializable
{
    /**
     * @var Sum|null
     */
    private $sum;

    /**
     * Returns Sum.
     */
    public function getSum(): ?Sum
    {
        return $this->sum;
    }

    /**
     * Sets Sum.
     *
     * @maps sum
     */
    public function setSum(?Sum $sum): void
    {
        $this->sum = $sum;
    }

    /**
     * Converts the Views1 object to a human-readable string representation.
     *
     * @return string The string representation of the Views1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Views1', ['sum' => $this->sum]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->sum)) {
            $json['sum'] = $this->sum;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
